### ISSUE TITLE
IE11 tests usually fail by timing out after running all tests

### ISSUE THREAD

**Issue by bicknellr** [lit/lit#1915] opened 2021-05-20 20:31 UTC
## Description

The IE11 tests on the `main` branch usually fail by timing out at the very end, even if all of the tests themselves pass. ([The `main` branch commit history page](https://github.com/lit/lit/commits/main) shows most recent commits as having failed.) This makes it easier to accidentally merge IE11-specific bugs because the pass/fail indication displayed on the PR page doesn't currently align with what we consider passing. We need to figure out what's causing these timeouts so that the action will report the correct result.

## Acceptance criteria

The IE11 tests on the `main` branch should correctly indicate their pass/fail state when reported to the PR's checks (and they should pass).

**Comment by kevinpschaaf** [comment] 2021-05-20 21:49
Closing as dupe of https://github.com/lit/lit/issues/1550

**Closed by kevinpschaaf** 2021-05-20 21:49 UTC
Labels: Focus Area: Core Libraries
