### ISSUE TITLE
Host Disconnected lifecycle callback not called when controller removed.

### ISSUE THREAD

**Issue by Vac1911** [lit/lit#1861] opened 2021-05-07 20:10 UTC
## Description

When [host.removeController ](https://github.com/lit/lit/blob/228c74f34b6a7c819984ab09e3c5612b2d88549d/packages/reactive-element/src/reactive-element.ts#L765)is called, the lifecycle method [controller.hostDisconnected](https://github.com/lit/lit/blob/228c74f34b6a7c819984ab09e3c5612b2d88549d/packages/reactive-element/src/reactive-controller.ts#L67) should also be called.

This would make its behavior consistent with the behavior of [host.addController](https://github.com/lit/lit/blob/228c74f34b6a7c819984ab09e3c5612b2d88549d/packages/reactive-element/src/reactive-element.ts#L758) and [controller.hostConnected](https://github.com/lit/lit/blob/228c74f34b6a7c819984ab09e3c5612b2d88549d/packages/reactive-element/src/reactive-controller.ts#L59):
https://github.com/lit/lit/blob/228c74f34b6a7c819984ab09e3c5612b2d88549d/packages/reactive-element/src/reactive-element.ts#L748-L760
<hr />

If hostDisconnected is not called at this time, then it will never be called on that controller instance even when the original host's [disconnectedCallback](https://github.com/lit/lit/blob/228c74f34b6a7c819984ab09e3c5612b2d88549d/packages/reactive-element/src/reactive-element.ts#L848-L859) is fired.
https://github.com/lit/lit/blob/228c74f34b6a7c819984ab09e3c5612b2d88549d/packages/reactive-element/src/reactive-element.ts#L848-L859

Without this change, it would be unsafe to attach external event listeners _anywhere_ in the controller, as they may not get removed and cause memory leaks.

## Acceptance criteria

[host.removeController ](https://github.com/lit/lit/blob/228c74f34b6a7c819984ab09e3c5612b2d88549d/packages/reactive-element/src/reactive-element.ts#L765) calls [controller.hostDisconnected](https://github.com/lit/lit/blob/228c74f34b6a7c819984ab09e3c5612b2d88549d/packages/reactive-element/src/reactive-controller.ts#L67) on the controller it removed.

**Comment by 43081j** [comment] 2021-05-08 11:24
I'm not sure that semantically makes sense. 

You can remove a controller from a still connected host, in which case the host has not been disconnected from DOM. 

I think what you want is an additional lifecycle callback which is called when the controller is removed. You would then remove any event listeners in both callbacks in this case (when the element has been removed from dom but still has your controller, and when the controller has been removed).

**Comment by justinfagnani** [comment] 2021-08-20 18:31
I'm inclined to agree with @43081j - I don't want to call `hostDisconnected` if the host is still actually connected. Both `addController()` and `removeController()` are intended to be called by the controller instance itself. I think if a controller is going to remove itself with `removeController()` is can also invoke any cleanup logic - and share that cleanup logic with `hostDisconnected()`.

**Comment by justinfagnani** [comment] 2021-08-20 18:32
Since we're nearing an imminent release and need to lock down the API behavior for `removeController()` I'm going to close this as working as intended.

**Closed by justinfagnani** 2021-08-20 18:32 UTC
Labels: Focus Area: Core Libraries
