### ISSUE TITLE
CSS tied to Boolean Attribute not always working

### ISSUE THREAD

**Issue by xiki808** [lit/lit#1871] opened 2021-05-11 05:32 UTC
The below component is a switch component highlighted with the green box in the image. When clicking a switch, a redux state is updated, causing the component to rerender, if required (if the new state is opposite) and if so, slides the switch to the new state. The switch slides with CSS based on the input element's attribute checked.

Some switches effect other switches. A master switch controls the switches below, and the below switches, can change the master switch to on if at least one is on, or to off, if all are off.

```
export class Switch extends connect(store)(LitElement) {
  static get properties() {
    return {
      master: { type: Boolean },
      entities: { type: Array },
      _entityStateList: {
        type: Object,
        hasChanged(newVal, oldVal) {
          return checkState(newVal, oldVal);
        },
        state: true,
      },
    };
  }

  stateChanged(state) {
    this._entityStateList = filterEntityStateList(this.entities, state.hass.states);
  }

  constructor() {
    super();
    this.master = false;
    this.entities = [];
    this._state = false;
    this._entityStateList = {};
  }

  render() {
    return html`
      <label class="toggle">
        <input type="checkbox" ?checked="${this._getState()}" @click=${this._switchClickHandler} >
        <span class="slider"></span>
      </label>
    `;
  }

  _switchClickHandler() {
    let service = 'toggle';
    let changeEntities = this.entities;

    if (this.master) {
      service = !this._getState() ? 'turn_on' : 'turn_off';
    }

    callServiceWebSocket(changeEntities, 'light', service);
  }

  _getState() {
    return Object.values(this._entityStateList).some((value) => value === 'on');
  }

  static get styles() {
    return [styles];
  }
}
```

![image](https://user-images.githubusercontent.com/8024321/117763360-4a322600-b1f0-11eb-9720-3184f8b0bb87.png)

The DOM is updated accordingly and the checkbox attribute is present as it should, but sometimes CSS does not reflect what the DOM is printing.

If instead of using Boolean Attribute I use the code below, it works fine

```
return html`
      <label class="toggle">
        ${this._getState()
          ? html` <input type="checkbox" checked @click=${this._switchClickHandler} /> `
          : html` <input type="checkbox" @click=${this._switchClickHandler} /> `}
        <span class="slider"></span>
      </label>
    `;
```

Would be great to be able to use Boolean Attribute in these situations, I need to introduce `disabled` attribute too and with if statements this code will look messy.

I'm using the following version:
```
    "lit": "^2.0.0-rc.2",
    "lit-element": "^3.0.0-rc.2",
```

**Comment by sorvell** [comment] 2022-01-14 23:55
Closing this due to age. Please open a new issue with a reproduction of the issue if the problem remains, ideally using [lit.dev/playground](https://lit.dev/playground/). Thanks!

**Closed by sorvell** 2022-01-14 23:55 UTC
