### ISSUE TITLE
[ssr] "window is not defined" on SSR.

### ISSUE THREAD

**Issue by FriedRiceNoodles** [lit/lit#3770] opened 2023-03-29 07:24 UTC
### Which package(s) are affected?

SSR (@lit-labs/ssr)

### Description

Seems the "window" has been delete from shim since https://github.com/lit/lit/issues/2453, But there is still a "window" in the prod bundle of some UI libraries such as "shoelace".
<img width="894" alt="image" src="https://user-images.githubusercontent.com/53017934/228454744-09723678-308f-4dff-96a4-7603114ef424.png">
@augustjk Have you ever encountered this problem during this test?https://github.com/shoelace-style/shoelace/issues/778

### Reproduction

```javascript
/* server side */
 import '@lit-labs/ssr/lib/install-global-dom-shim.js';
// ...blablabla

/* client */
//Use shoelace or someother UI library built with lit.
```

### Workaround

Not yet.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

lit@2.6.1

### Browser/OS/Node environment

- node 16.15.0
- remix 1.14.0

**Comment by FriedRiceNoodles** [comment] 2023-03-29 14:58
> I encountered this as well, but it looks like #2453 has been closed [without removing anything](https://github.com/lit/lit/issues/2453#issuecomment-1033139355).

https://github.com/lit/lit/issues/2393#issuecomment-1376378597

**Comment by justinfagnani** [comment] 2023-03-29 15:28
Shoelace unfortunately bundles Lit, so it might not be up to date with the Lit versions that no longer reference `window`. Shoelace's bundling of Lit also prevents developers from using our different builds, like the development build or the Node build. See https://github.com/shoelace-style/shoelace/issues/559

**Comment by FriedRiceNoodles** [comment] 2023-03-31 06:02
> Shoelace unfortunately bundles Lit, so it might not be up to date with the Lit versions that no longer reference `window`. Shoelace's bundling of Lit also prevents developers from using our different builds, like the development build or the Node build. See [shoelace-style/shoelace#559](https://github.com/shoelace-style/shoelace/issues/559)

Yes, I saw it, but it seems that lit does use `window` in some places.
![image](https://user-images.githubusercontent.com/53017934/229017359-4a533dac-03dd-4206-bef1-183912b5f174.png)
![image](https://user-images.githubusercontent.com/53017934/229017403-00094385-b989-4f6a-937b-86b459cd894d.png)
That means even if shoelace doesn't bundles Lit, instead of I import Lit in my project, then my prod bundle will still exist a 'window' reference.

**Comment by EAzari** [comment] 2023-04-01 18:39
@justinfagnani we shouldn't use `globalThis` everywhere? including browsers?

**Comment by augustjk** [comment] 2023-04-03 17:29
@EAzari `globalThis` is fine to use everywhere for modern browsers. We've kept that `NODE_MODE` ternary for IE11 support of our browser builds but that'll be dropped in Lit 3.0.

**Comment by justinfagnani** [comment] 2023-04-14 23:14
I'm going to close this since the problem is with Shoelace, not Lit. They could bundle a newer version of Lit, but are also working on unbundling Lit altogether.

**Closed** 2023-04-14 23:14 UTC

**Comment by claviska** [comment] 2023-04-25 21:47
There's an open PR that I need to review again, but yes, we're looking at providing an unbundled version of Shoelace in the near future — hopefully the next release.

https://github.com/shoelace-style/shoelace/pull/1298

**Comment by justinfagnani** [comment] 2023-06-21 00:55
For anyone subscribed here, Shoelace 2.5 unbundles Lit, which solves this issue! Thanks to the Shoelace team!
