### ISSUE TITLE
CSSResultArray leaks

### ISSUE THREAD

**Issue by busynest** [lit/lit#2650] opened 2022-03-19 13:43 UTC
# Description

CSSResultArray loads all non lazy-loaded Modular styles into primary HTML Document's `<head>` tag.  This causes glitches to show CSS crossed out in the Inspector, but actually takes first order and overrides.

# Steps to Reproduce

Document Structure:

HTML:
`<application-shell>`

doc 1: CSS Modules Document
```
export const _colours : CSSResult = css` :host { color: green; } `;
export const _appShell : CSSResult = css` :host { color: blue; } `;
export const _homePage : CSSResult = css` :host { color: red; } `;
```

doc 2: application-shell
`static get styles():CSSResultArray { return [ _colours, _appShell ...`

doc 3: home-page
`static get styles():CSSResultArray { return [ _colours, _homePage ...`

## Expected Results

I expected my `<head>` to be clean and isolated from Modules. 

A similar <style> tag is injected into <head> when I write:
```
render() {
   return html` <style>  a { color: green; } </style>`
}
```

## Actual Results

Result is `<a>` styles from another CSS Module are styling a differend Module, becuase HTML document is styled.
CSS is crossed out in the Inspector, but actually takes first order and overrides.

**Comment by busynest** [comment] 2022-03-19 13:51
There is also no way to self style the upper most Module like this: <style ?data-active="${this.theme}"> </style>. To produce this: :host[data-on] { color: #000; }

This is why I was thinking to try styleMap

**Comment by busynest** [comment] 2022-03-19 14:48
Therefore, ( CSSResultArray + style tag ) both behave in one way, but styleMap is should be better because it's serialization. It's should be better for shared styles.

**Comment by busynest** [comment] 2022-03-19 17:24
Even though CSSResultArray injects `<style>` tags into the `<head>` tag, I may be wrong about them leaking. it's a complex app.

**Comment by justinfagnani** [comment] 2022-03-19 17:24
> CSSResultArray loads all non lazy-loaded Modular styles into primary HTML Document's <head> tag

This isn't the case. Do you have a reproduction to show what you're seeing?

**Comment by busynest** [comment] 2022-03-19 21:03
I will make a stackblitz, but it's nothing new. 
I checked to see if it was different in production, same injection of style tags.
For now, here is an image of the production `<head>`: https://contractorscentre.com/images/error.png
If i'm wrong then sorry for the time.

**Comment by bathos** [comment] 2022-03-20 02:14
@busynest I didn’t understand what you were describing in the “could inline styles...” thread, but here it looks like you’re talking about ShadyCSS. ShadyCSS does use document level stylesheets to simulate scoping. That’s roughly its whole job description.

I think Lit includes _support for_ the ShadyDOM/ShadyCSS libraries by looking for their shared globals + checking if the library reports as “inUse.” However those libraries are neither part of Lit nor are they required to use it. 

Shadow DOM can’t be polyfilled quite faithfully in JS, but most of the associated capabilities can be approximated by trading away some other facet of the real thing: encapsulation, performance, correctness, etc. Putting guts on the outside can be necessary to get some aspect of that job done, so for example after scope simulation, when the premise is “what if there are no ShadowRoots,” then there’s only one place a stylesheet could ever go. The ShadyCSS readme describes its caveats and [limitations (https://github.com/webcomponents/polyfills/tree/master/packages/shadycss#limitations) including this one.

Do you mean to be using ShadyCSS here? Unless it’s a specific requirement that you must support unmaintained browsers from ~2017 or earlier, I’d suggest avoiding this. Because ShadyDOM & ShadyCSS cannot be “transparent,” there’s a cost/risk in play that one might not expect for a polyfill-like-thing. (Nothing but respect for its maintainers to be clear, what I’m describing isn’t  an issue of quality, just circumstance.)

**Comment by busynest** [comment] 2022-03-20 02:51
@bathos Okay, I need to think about what you said. For now, it looks like Material Design listened last time I said it. The tool is here: https://www.npmjs.com/package/@material/material-color-utilities

**Comment by bathos** [comment] 2022-03-20 03:50
@busynest I don't understand the relationship between Material Design and anything here. However I'm _pretty_ sure you're not a markov chain cause I looked at your linked site and can see that you're indeed loading ShadyCSS and ShadyDOM there. They are active along with a vast web of other polyfills and patches. None of it is needed AFAICT.

![// A wide range of builtins (truly vast seemingly - just checking at random, I got more hits than misses) is
// getting unilaterally replaced with JS-layer reimplementations and/or patches. None of this is necessary as
// the browser I am in already implements these APIs natively. In fact, the fakes are *missing* capabilities
// that the browser actually does implement. It's kinda like the "opposite" of polyfilling.
[document.querySelector, Event, CustomElementRegistry, customElements, document.createElement, ShadowRoot]
(6) [ƒ, ƒ, ƒ, P, ƒ, ƒ]0: ƒ (a)1: ƒ b(c,d)2: ƒ P(a)3: P {U: Map(0), V: Map(8), la: Map(8), da: false, fa: Map(0), …}4: ƒ (b)5: ƒ wc(a,b,c)length: 6[[Prototype]]: Array(0)
// In fact, there are not even custom elements on this site. Everything is fake. This is pretty wild!
[ ...document.querySelectorAll(":defined") ].filter(e => e.localName.includes("-")).length
0
document.querySelector("application-shell").matches(":defined");
false](https://user-images.githubusercontent.com/6257356/159147271-86173d3e-9119-4deb-8417-99b391939838.png)

**Comment by busynest** [comment] 2022-03-20 04:53
@bathos nice, dude. This is good feedback. There is tons of homework to do. I don't mind retro. I was curious about the design questions because I don't know the professional design world. I sort of had a feeling someone will see all this easy, spread out coding objects. I sort of had a quick understanding how I must re-write it tightly, and fix all this non-element comment stuff. awesome ! Thanks, for I hope I get it right one day.

**Comment by busynest** [comment] 2022-03-20 05:16
I'll put back:   `customElements.define('application-shell', ApplicationShell);` everywhere, because I thought lit's `@customElement` took care of that.

**Comment by busynest** [comment] 2022-03-20 05:53
some of your tests might have advertisement objects from google adsense.

**Comment by busynest** [comment] 2022-03-21 15:02
From what I understand, The js thread is single. That’s why I transpile down, and I guess the result is no-framework.  That’s what I meant by integration. Because Modular Design is only for design, once a system is combined, it must cristalize (projectized framework). I am always thinking about reductions to a single result. So that Markov Chain thing doesn’t seem to mean much to me. If you meant the outcome of the search engine on my site, it’s geocoded. It works well, everything is just incomplete and changing.

I may be wrong about assumptions, I am trying to figure it out.

**Comment by busynest** [comment] 2022-03-21 16:20
Could the google please make a built in redux tool. There are many members of the membrane

**Comment by bathos** [comment] 2022-03-21 18:37
> So that Markov Chain thing doesn’t seem to mean much to me.

Sorry, this was just a joke. I meant that because I was finding it difficult to understand how your posts are related to one another and what they were trying to communicate, I was not 100% sure if maybe I was “talking to” a bot. That’s why I checked the link to your site, where I could see that it was consistent with what you had shown here. This made it clear that you’re a real person! :)

The communication challenge is still there, though. I can only be confident about what was meant by a few bits and pieces of what you’ve said and I’m guessing some of the terminology being used is not correct. Perhaps there’s a language barrier in play or you are learning new stuff on your own, both of which can make tech discussion pretty touch at first! This is totally okay, of course, but I suspect you’re investigating several very different issues of which none may actually be related to Lit, so this particular repo may not be the right place to explore them.

**Comment by busynest** [comment] 2022-03-21 19:12
Cool, thanks for speaking up. I do suck at communicating. I do have multiple goals to figure out and they do get mixed up. You guy are the smart ones. Thank you for everything.

**Comment by bathos** [comment] 2022-03-21 21:32
@busynest I’m not a lit maintainer, just another dev who happened to see this thread and recognized that your screenshot showed what appears to be the normal behavior of ShadyCSS, a different library from Lit.

I gotta correct you about something though. The “smart ones” thing is dangerous! Different devs with different levels of experience, intuition, and familiarity with (specific) problem spaces and ideas can sometimes seem unapproachably “smart” if you do not _yet_ have comparable experience, intuition, and familiarity in the same domains. But there’s no smart / not smart divide. No one ever has a complete picture. We also all begin with some confusing, blurry, and (stupendously) incorrect images. Over time, the image will become sharper and sharper. It doesn’t happen uniformly and no matter what it will include mistakes. But it’ll still be getting just a little bit sharper every day. Your image sharpening engine is already running. For most folks it’s driven by some combination of persistent curiosity and a _lot_ of repetition. It does not depend on “intelligence” much but it does take time.

An awkward step often occurs early on (and it can recur at any time later!). Because we’re entering some new domain, we find ourselves absorbing a _lot_ of new vocabulary and concepts all at once. Oddly, new words often become embedded in our minds before we actually “know” what they mean. It’s like we can need to “try them out” to figure out what they mean. The less prior context we have, the more likely it will be that this to happen. If the words are like puzzle piece, this is like solving a jigsaw puzzle in a dark room with a missing box. You don’t know what the picture is, but you can kinda see and feel the shapes of the pieces. Those are the words, and if you can figure out how they connect to each other, a lot of other things, including their actual meanings, can suddenly fall into place like magic. It sounds backwards, but it’s pretty natural!

A closely related thing can also occur when we try to solve _specific problems_ from such a place. The lack of bearings will mean that once again there’s some feeling around in the dark. We might think something like “okay, well ... i bet this is what `<unplaced-puzzle-piece>` is about — so let’s try that next!” We say that to ourselves with an odd kind of confidence because we often have no idea at all if it’s true! But there’s a reason for that: we’re _tricking ourselves._ We know on some level (especially if we feel frustrated or lost) that _lying to ourselves_ about having the answer is the only way to motivate ourselves to take the next steps that will actually let us determine whether or not it is the answer. If we were wrong, we still learned that’s not where this puzzle piece goes. The process may then repeat.

Both of those things are valid ways for developers to tackle problems and are essentially unavoidable when they have very little stuff to “grab onto”. But they also share another very important characteristic: _they are not communicative!_ They are _internal_ strategies which run on your ... “speculation engine” loop thingie. You’ve got one of these for sure lol (do you ever!), but you’re wearing it inside out!

So when seeking assistance from other, I’d suggest that after explain what you observed, how you observed it, and why it seemed wrong or surprising to you, no further speculation be included. The speculation engine only works if it’s pointing towards the _inside_ of your mind. It’s a feedback loop that operates on _your_ knowledge space! Facing outwards, it’ll be like a megaphone shouting random words at passersby. Might frightening some small animals too :) Cause remember, other folks don’t know what your internal picture looks like or which pieces you’re still trying to find homes for. They won’t know where the questions end and the guesses begin and will get confused even if they might otherwise been able to help.

---

I know this is an odd response but I just have a hunch from trying to follow the two threads that you may really need this info. I could be totally wrong though, so sincere apologies if this was presumptuous / landed wrong. I don’t have definite knowledge of where you’re at, to be clear.  But it really is important at least to remember that the folks who help are _not_ smarter than you. They’re just you from the future.

**Comment by busynest** [comment] 2022-03-22 00:32
Thank you very much! I really do appreciate the feedback, because I never hear it. I will save this a re-read it out of respect. It is really nice to see that we actually do think alike. I had a good conversation before this, so I came in hot, Most of my anxiety is because I am working normal job, and don't actually have time to chat. I agree not to idolize devs, and completely everything else that you said. If there is one thing I could say, then I hope for a future where technology will empower all businesses, and people. Hopefully without too much gatekeeping lol

**Closed** 2022-03-22 01:39 UTC

**Comment by bathos** [comment] 2022-03-22 02:01
> because I never hear it. 

Yeah, figured. (Had no devs to talk to; had no clue that being able to speak about code was already the only missing “pillar”.)

> Most of my anxiety is because I am working normal job, and don't actually have time to chat

I know lol. (Slept in the back of the record store where I worked just to get one more hour coding.)

> Hopefully without too much gatekeeping lol.

You gotta close this thread cause we’ve drifted pretty far outside of Github norms here lol (my fault), but it was nice to figure out exactly _why_ I felt compelled to answer your questions despite just being a lurker here. Good luck, birthmark buddy :)

**Comment by busynest** [comment] 2022-03-22 03:22
zero gatekeeping. That’s I hope the future is good.
