### ISSUE TITLE
[lit-html] How to spread SVG attributes?

### ISSUE THREAD

**Issue by aztack** [lit/lit#1978] opened 2021-06-24 04:21 UTC
## Description
I want to pass svg attributes like following:
```typescript
function svgIcon(paths: TemplateResult<2>[], props: Props) {
  return svg`
    <svg class="my-icon-svg" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" ${spread(props)}>
      ${paths}
    </svg>
  `;
}
```

I searched in the issues but did not find any solution.
The `spread` directive is still under discussion.
Is there a workaround?

**Comment by justinfagnani** [comment] 2021-06-25 00:22
I'm working on the spread directive now. I'll make sure it works with SVG.

**Comment by justinfagnani** [comment] 2022-06-17 23:50
Dupe of #923

**Closed by justinfagnani** 2022-06-17 23:50 UTC
