### ISSUE TITLE
If Class is necesary for Lit ? (i hate OOP)

### ISSUE THREAD

**Issue by tvortsa** [lit/lit#4694] opened 2024-07-06 19:57 UTC
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

just question about Class? 
Can i dont use class in Lit?

### Alternatives and Workarounds

Class

**Comment by justinfagnani** [comment] 2024-07-06 20:30
This should be a GitHub discussion or a topic on our Discord channel. But...

Custom elements necessarily have to extend from HTMLElement. That's just how the platform works, and is similar for extending other native classes like Event, Map, etc. Classes are simply everywhere in JS and the DOM, there's really no avoiding _using_ them.

That said, there are two approaches you could take:

1. Write a wrapper around LitElement that makes it look "functional". You could write a function, like `defineElement()` that takes all the data you need to define and element: a render function, a tag name, property declarations, styles, event handlers, lifecycle callbacks, etc.

  It might look like this:

```ts
export const MyElement = defineElement('my-element', {
  properties: {
    greeting: {type: String},
    subject: {type: String},
  },
  styles: css`
    :host { display: block; }
  `,
  render() {
    return html`
      <h1>${this.greeting}, ${subject}</h1>
      <button @click=${this.sayHi}>Hi</button>
    `;
  },
  methods: {
    sayHi() { console.log('Hi'); }
  }
});
```

This quickly gets tricky when you get to lifecycle hooks like `connectedCallback()`, or `update()`, where you have to call `super`. `super` isn't available outside of classes, so you have to invent some other way of calling into super methods, and it'll be non-standard so normal JS programmers will have to learn how to use it. You could also not allow overriding methods, but map something like hooks over top of the LitElement + custom element lifecycles. I'm not sure how many gaps that leaves.

There is a project called [Haunted](https://github.com/matthewp/haunted) that made a "functional" wrapper, with hooks, around LitElement. I don't think it's maintained anymore though.

But you can also see that this just starts looking like a class, so... why not use a class as the container for these items? The syntax is only slightly different, but it's more concise and the semantics implied by the syntax are more standard.

2. Learn to not hate classes.

This may sound flippant, but it's really not. Classes are declarative and combine behavior with state. They're nearly tailor-made for UI components. Most other "functional" UI component approaches have ended up emulating classes - and often poorly. React hooks are very much like non-standard (and unintuitively behaved, IMO) replacements for fields (useState) and methods (useEffect). Svelte components look like modules but _behave_ very much like classes, where top-level fields become instance properties.

Lit's classes can be written particularly declaratively and functionally. The styles and properties blocks (or fields) are just declaring necessary parts of the component definition. The `render()` can be very pure - only accessing instance state and never mutating it. It's very similar to a functional component with a few extra declarative parts.

I hope that helps.

**Comment by tvortsa** [comment] 2024-07-09 07:13
Thanks for the detailed answer, but you could just write "no" and save us
both time :)

I don’t need to “learn” classes and OOP, because I started with Java and
worked in OOP for five years, you should have learned to do without the
“mandatory” OOP, the react.js developers learned and switched from class
components to functional ones a long time ago .

The problem with the OOP and its supporters is not the OOP itself, but the
religious conviction that without the OOP it is impossible.

This is actually what I wanted to know about Lit, thank you!

сб, 6 июл. 2024 г. в 23:30, Justin Fagnani ***@***.***>:

**Comment by sorvell** [comment] 2024-07-09 22:43
Just for clarity, custom elements are implemented in the web platform [via classes](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements#implementing_a_custom_element). 

The most idiomatic way to use Lit is via [custom elements](https://lit.dev/docs/components/defining/), but you can also use Lit's templating system [stand alone](https://lit.dev/docs/libraries/standalone-templates/). When used this way, there is no requirement to use classes.

**Comment by tvortsa** [comment] 2024-07-10 09:57
Thank you, i will try the templating system

ср, 10 июл. 2024 г., 01:44 Steve Orvell ***@***.***>:

**Comment by justinfagnani** [comment] 2024-10-02 01:40
Closing this as working as intended.

**Closed by justinfagnani** 2024-10-02 01:40 UTC
