### ISSUE TITLE
@customElement could automatically add meta information about tagName to class

### ISSUE THREAD

**Issue by mcjazzyfunky** [lit/lit#2008] opened 2021-07-15 16:54 UTC
## Description

When you are defining custom elements by using the `@customElement` decorator, it would be nice if the meta information about the tag name would be added automatically to the class/constructor. For example via `clazz[Symbol.for('lit.tagName')] = ..`. There are some use cases where you have the class/constructor but would also like to know the corresponding tag name, for example to determine a namespace or subcategory name used for building translation keys. Currently you have to use a an custom decorator or a static field or whatever for that, which feels a bit cumbersome.

**Comment by justinfagnani** [comment] 2021-07-15 17:02
Duplicate of #1996

We don't really want to do this since it would be unique behavior for not just LitElements but only LitElements that use the `@customElement()` decorator. We'd much rather people use a way that works with all elements instead, and that works with the upcoming scoped custom element registries.

See https://github.com/WICG/webcomponents/issues/566 for standards discussion.

**Closed by justinfagnani** 2021-07-15 17:02 UTC
Labels: Focus Area: Core Libraries

**Comment by Odas0R** [comment] 2024-06-09 17:17
I know this is closed, but:

```ts
import { customElement as litCustomElement } from 'lit/decorators.js';

export function customElement(tagName: string) {
  return function (constructor: Function) {
    litCustomElement(tagName)(constructor as CustomElementConstructor);

    Object.defineProperty(constructor, 'name', {
      value: tagName,
      writable: false,
    });
  };
}
```

// @customElement("some-element")
// export class CustomElement extends LitElement {
// ... 
//
// CustomElement.name
// Output: "some-element"

**Comment by justinfagnani** [comment] 2024-06-09 17:26
Again, the problem here is that this adds unique behavior only to elements that use the decorator, so it's not very interoperable. No utility could rely on this property being present, as elements not defined with this constructor wouldn't have it.

**Comment by Odas0R** [comment] 2024-06-09 17:35
I've read the spec and yes, I totally support it, and of course, that's the way to go.

For now, the only way is to "hack" it, haha. I'll change to property to be `getName()`

Thank you so much for your work and concern!
