### ISSUE TITLE
"_Φ" and "_Σ" are not invalidate identifier in chrome extensions context

### ISSUE THREAD

**Issue by ypchris** [lit/lit#1962] opened 2021-06-16 09:43 UTC
I'm developing a chrome extension with lit.  Chrome throws a error: Uncaught SyntaxError: Invalid or unexpected token about '"_Φ": () => (/* binding */ _Φ)'. I change Φ and Σ to other word. Then Chrome works.

**Comment by justinfagnani** [comment] 2021-06-17 18:13
Duplicate of #1958

**Closed by justinfagnani** 2021-06-17 18:13 UTC
