### ISSUE TITLE
Property converter does not work with @lit/react

### ISSUE THREAD

**Issue by haiphan** [lit/lit#4717] opened 2024-07-30 11:37 UTC
### Which package(s) are affected?

React (@lit/react)

### Description

I am trying to use the @lit/react wrapper to create a wrapper react component for the lit element. But it does not work with property converter. I have an example in this link. When passing the property value to the wrapped react component, the value is assigned directly to the property without going through the custom converter.

In the example, if I use demo-greeting directly the property assignment goes through the converter, but not when using DemoGreeting.

https://lit.dev/playground/#sample=examples%2Freact-basics&gist=552647e2fab82fdfceec23a1398f8f8c

### Reproduction

https://lit.dev/playground/#sample=examples%2Freact-basics&gist=552647e2fab82fdfceec23a1398f8f8c

### Workaround

I have not found a workaround.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

Failing in 1.0.5

### Browser/OS/Node environment

Browser: Chrome 126.0.6478.127 (Official Build) (x86_64)
OS: macOS 14.5

**Comment by augustjk** [comment] 2024-07-30 16:53
Thank you for the repro!

This is because the property converter only runs when converting an attribute value to a property value. Currently, using bare custom element tags directly in React will always set props as attribute values, triggering the converter. Starting React 19, React will use the same `in` check like the `@lit/react` wrapper is doing and set them as property values, bypassing the custom converter. You can see this behavior when using the `@beta` tag of React: https://lit.dev/playground/#sample=examples%2Freact-basics&gist=c38dd4542f78213fee9a959350bcec77

Unfortunately React JSX doesn't have syntax to differentiate between setting as attribute or setting as property.

If you'd like the conversion to happen regardless of whether the value is set as attribute or property, it would be better to either use a custom accessor (getter or setter), or use the `willUpdate` lifecycle to derive the new value you want. See https://lit.dev/docs/components/properties/#accessors-custom

**Comment by augustjk** [comment] 2024-08-02 18:03
Closing issue since this is working as intended. Feel free to comment if there are other concerns.

**Closed by augustjk** 2024-08-02 18:03 UTC
