### ISSUE TITLE
Not rendering default slot value when multiple lines

### ISSUE THREAD

**Issue by hersing** [lit/lit#1939] opened 2021-06-02 17:06 UTC
When having slots containing default values, the default values will not render if the components is used with a newline in it. Look at this example:

```javascript
import { LitElement, html } from 'lit';
import { customElement } from 'lit/decorators.js';

@customElement('my-element2')
class MyElement2 extends LitElement {
    render(){
        return html`
            <slot name="someSlot">default content for "someSlot"</slot>
            <slot>default content for slot</slot>`;
      }
}

@customElement('my-element')
class MyElement extends LitElement {
    render(){
        return html`
            <my-element2>
               <span slot="someSlot">This is some content</span>
            </my-element2>`;
    }
}

```

I would expect `my-element` to show "This is some content" and "default content for slot" but it only shows "This is some content". The only way of making it show both is by writing:
 ` <my-element2><span slot="someSlot">This is some content</span></my-element2>`
And in my opinion that's going to be really unreadable if you imagine having multiple slots to fill.

**Comment by aomarks** [comment] 2021-06-02 17:18
This is the expected behavior of the built-in `<slot>` element. Any Element or Text node is slottable (https://dom.spec.whatwg.org/#concept-slotable), and whitespace is a Text node.

This has bit me before, though. It's definitely a gotcha to be aware of. In an example like the one you gave, I'd suggest having two named slots instead of a named slot and a default slot.

Closing since this is not Lit specific.

**Closed by aomarks** 2021-06-02 17:18 UTC

**Comment by justinfagnani** [comment] 2021-06-02 17:37
This is where we talk about it in the docs: https://lit.dev/docs/components/shadow-dom/#specifying-slot-fallback-content

Not sure if there's anything we can do to clarify that.
