### ISSUE TITLE
details tag boolean attribute bug.

### ISSUE THREAD

**Issue by Thomas-Langlais** [lit/lit#1909] opened 2021-05-18 18:48 UTC
# Description
When using the `<details>` element, trying to set the `open` attribute using a state or property will always make it one step behind.

# Steps to Reproduce

1. Copy the code into the lit.dev playground
```ts
import { LitElement, html } from 'lit';
import { customElement, state } from 'lit/decorators.js';

@customElement('cus-appendix')
class Appendix extends LitElement {

  @state()
  private open = false;

  render() {
    return html`<details class="appendix" ?open=${this.open}>
      <summary class="appendix__title"
      @click=${this.toggleOpen}>
      <slot name="title">
        <span>Appendix</span>
      </slot>
    </summary>
      <div class="appendix__content">
        <slot></slot>
      </div>
    </details>`;
  }

  toggleOpen() {
    this.open = !this.open;
  }
}
```
2. Alter the index.html to have a `<cus-appendix></cus-appendix>` tag
3. click on the custom element.

## Live Reproduction Link
I am using typescript, if anyone knows to do this on stackblitz please let me know!

## Expected Results
The element should update the state and render the attribute open.

## Actual Results
1. It toggles the attribute on, and then off for the first click.
2. Subsequent clicks toggles the div content, but the state variable is always the opposite upon render().

I found that immediately after the execution of `this.update(changedProperties);` from `ReactiveElement.performUpdate()` that
the attribute is rendered correctly but somewhere after that, it removes the attribute.

## Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by justinfagnani** [comment] 2021-05-18 18:55
The underlying open state of the detail element is being changed outside of Lit by the browser. In order to get Lit to understand this and do change detection against the live value, you need to use the `live()` directive.

I would probably bind against the detail element's `open` property as well.

```ts
import { LitElement, html } from 'lit';
import { customElement, state } from 'lit/decorators.js';
import { live } from 'lit/directives/live.js';

@customElement('cus-appendix')
class Appendix extends LitElement {

  @state()
  private open = false;

  render() {
    return html`<details class="appendix" .open=${live(this.open)}>
      <summary class="appendix__title"
      @click=${this.toggleOpen}>
      <slot name="title">
        <span>Appendix</span>
      </slot>
    </summary>
      <div class="appendix__content">
        <slot></slot>
      </div>
    </details>`;
  }

  toggleOpen() {
    this.open = !this.open;
  }
}```

**Comment by Thomas-Langlais** [comment] 2021-05-18 19:19
Could remove the need for using the live directive by doing the following?

```ts
render​(​)​ ​{​
    ​return​ ​html​`​<​details​ ​class​="​appendix​" ​.open​=​${​this​.​open​}​>​
​      ​<​summary​ ​class​="​appendix__title​"​
​      ​@click​=​${​this​.​toggleOpen​}​>​
​      ​<​slot​ ​name​="​title​"​>​
​        ​<​span​>​Appendix​</​span​>​
​      ​</​slot​>​
​    ​</​summary​>​
​      ​<​div​ ​class​="​appendix__content​"​>​
​        ​<​slot​>​</​slot​>​
​      ​</​div​>​
​    ​</​details​>​`​;​
  ​}​
```

Or would run into the same problem as before?

**Comment by Thomas-Langlais** [comment] 2021-05-19 18:22
The solution you proposed does not work as expected in the playground environment either.
@justinfagnani

**Comment by justinfagnani** [comment] 2021-05-20 18:39
For the reproduction link, you can just link to the lit.dev playground directly.

**Comment by AndrewJakubowicz** [comment] 2021-05-20 22:07
Created a [repro in the playground](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQgeyBMaXRFbGVtZW50LCBodG1sIH0gZnJvbSAnbGl0JztcbmltcG9ydCB7IGN1c3RvbUVsZW1lbnQsIHN0YXRlIH0gZnJvbSAnbGl0L2RlY29yYXRvcnMuanMnO1xuaW1wb3J0IHsgbGl2ZSB9IGZyb20gJ2xpdC9kaXJlY3RpdmVzL2xpdmUuanMnO1xuXG5AY3VzdG9tRWxlbWVudCgnY3VzLWFwcGVuZGl4JylcbmNsYXNzIEFwcGVuZGl4IGV4dGVuZHMgTGl0RWxlbWVudCB7XG5cbiAgQHN0YXRlKClcbiAgcHJpdmF0ZSBvcGVuID0gZmFsc2VcblxuICByZW5kZXIoKSB7XG4gICAgY29uc29sZS5sb2coJ3JlbmRlcicsIHRoaXMub3BlbilcbiAgICByZXR1cm4gaHRtbGA8ZGV0YWlscyBjbGFzcz1cImFwcGVuZGl4XCIgP29wZW49JHtsaXZlKHRoaXMub3Blbil9PlxuICAgICAgPHN1bW1hcnkgY2xhc3M9XCJhcHBlbmRpeF9fdGl0bGVcIlxuICAgICAgQGNsaWNrPSR7dGhpcy50b2dnbGVPcGVufT5cbiAgICAgIDxzbG90IG5hbWU9XCJ0aXRsZVwiPlxuICAgICAgICA8c3Bhbj5BcHBlbmRpeDwvc3Bhbj5cbiAgICAgIDwvc2xvdD5cbiAgICA8L3N1bW1hcnk-XG4gICAgICA8ZGl2IGNsYXNzPVwiYXBwZW5kaXhfX2NvbnRlbnRcIj5cbiAgICAgICAgPHNsb3Q-PC9zbG90PlxuICAgICAgPC9kaXY-XG4gICAgPC9kZXRhaWxzPmA7XG4gIH1cblxuICB0b2dnbGVPcGVuKCkge1xuICAgIHRoaXMub3BlbiA9ICF0aGlzLm9wZW47XG4gIH1cbn0ifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPGhlYWQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vc2ltcGxlLWdyZWV0aW5nLmpzXCI-PC9zY3JpcHQ-XG48L2hlYWQ-XG48Ym9keT5cbiAgPGN1cy1hcHBlbmRpeD5cbiAgPHA-SGVsbG8sIFdvcmxkITwvcD5cbiAgPC9jdXMtYXBwZW5kaXg-XG48L2JvZHk-XG4ifV0).

Logging `this.open` at the start of the `render` method. Does seem to be one step behind.
There is a single click no-op before it starts working as well.

**Comment by AndrewJakubowicz** [comment] 2021-06-03 18:23
Hi @Thomas-Langlais,

The issue is happening because the `open` state and event behavior are competing.
This can be resolved by preventing the default click behavior on the `details` tag.

[Example in lit playground](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQgeyBMaXRFbGVtZW50LCBodG1sIH0gZnJvbSAnbGl0JztcbmltcG9ydCB7IGN1c3RvbUVsZW1lbnQsIHN0YXRlIH0gZnJvbSAnbGl0L2RlY29yYXRvcnMuanMnO1xuaW1wb3J0IHsgbGl2ZSB9IGZyb20gJ2xpdC9kaXJlY3RpdmVzL2xpdmUuanMnO1xuXG5AY3VzdG9tRWxlbWVudCgnY3VzLWFwcGVuZGl4JylcbmNsYXNzIEFwcGVuZGl4IGV4dGVuZHMgTGl0RWxlbWVudCB7XG5cbiAgQHN0YXRlKClcbiAgcHJpdmF0ZSBvcGVuID0gZmFsc2VcblxuICByZW5kZXIoKSB7XG4gICAgY29uc29sZS5sb2coJ3JlbmRlcicsIHRoaXMub3BlbilcbiAgICByZXR1cm4gaHRtbGA8ZGV0YWlscyBjbGFzcz1cImFwcGVuZGl4XCIgP29wZW49JHtsaXZlKHRoaXMub3Blbil9PlxuICAgICAgPHN1bW1hcnkgY2xhc3M9XCJhcHBlbmRpeF9fdGl0bGVcIlxuICAgICAgQGNsaWNrPSR7dGhpcy50b2dnbGVPcGVufT5cbiAgICAgIDxzbG90IG5hbWU9XCJ0aXRsZVwiPlxuICAgICAgICA8c3Bhbj5BcHBlbmRpeDwvc3Bhbj5cbiAgICAgIDwvc2xvdD5cbiAgICA8L3N1bW1hcnk-XG4gICAgICA8ZGl2IGNsYXNzPVwiYXBwZW5kaXhfX2NvbnRlbnRcIj5cbiAgICAgICAgPHNsb3Q-PC9zbG90PlxuICAgICAgPC9kaXY-XG4gICAgPC9kZXRhaWxzPmA7XG4gIH1cblxuICB0b2dnbGVPcGVuKGUpIHtcbiAgICBlLnByZXZlbnREZWZhdWx0KClcbiAgICB0aGlzLm9wZW4gPSAhdGhpcy5vcGVuO1xuICB9XG59In0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL3NpbXBsZS1ncmVldGluZy5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDxjdXMtYXBwZW5kaXg-XG4gIDxwPkhlbGxvLCBXb3JsZCE8L3A-XG4gIDwvY3VzLWFwcGVuZGl4PlxuPC9ib2R5PlxuIn1d)

Please let me know if this doesn't fix your issue.
Thank you!

**Closed by AndrewJakubowicz** 2021-06-03 18:23 UTC
