### ISSUE TITLE
[labs/react] Prop/attribute handling for server-rendered wrapped components

### ISSUE THREAD

**Issue by augustjk** [lit/lit#3418] opened 2022-11-03 03:06 UTC
### Which package(s) are affected?

React (@lit-labs/react)

### Description

With https://github.com/lit/lit/pull/3128 merged, wrapped components can be (shallowly) server-rendered by React. However, all props found in the custom element class's prototype are collected and not passed to React, meaning those will not show up in the server-rendered markup of the host element.

This can cause janky behavior like the initial paint rendering a not-upgraded custom element, then the upgrade happens with no attributes set rendering with default props, then the `componentDidMount` lifecycle sets the props causing another potential update.

### Reproduction

TODO

### Workaround

Potential ways of handling as suggested by @sorvell:

1. Could just pass through all the props when `isServer` is true. We'd get poor behavior for complex props and corner cases but primitive values would work.
2. Do (1) but apply special handling for known element properties: (1) always pass primitive values, (2) always just JSON.serialize objects, (3) pass the value of [pseudo-code] this.getPropertyOptions(propName).toAttribute(reactPropValue)

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

1.1.0

### Browser/OS/Node environment

N/A

**Comment by steveworkman** [comment] 2023-04-18 14:41
I've created a sample project that shows the bug: https://github.com/steveworkman/lit-ssr-react

In summary:
- CSR components work fine
- SSR of raw lit components works fine
- SSR when using lit-labs/react wrapped components does not pass props or slots and no properties are reflected

This is with me manually wrapping the react components and not using the generator - though I believe the result would be the same.

**Comment by steveworkman** [comment] 2023-04-20 08:34
I've added another example to the reproduction above: `styled-components` and using `<Component as="simple-button">` which is a work-around for [styled components not supporting custom elements](https://github.com/styled-components/styled-components/issues/3179). It appears that as soon as you turn it into a react component, through the wrapper or not, the props are not passed into SSR

**Comment by ChellappanRajan** [comment] 2023-04-30 04:38
@augustjk I tried the workaround solution you suggested for the issue, and now it is working fine. Could you please confirm whether I have implemented it in the correct place?


      override render() {
        .......
        if(isServer){
          return createElement<React.HTMLAttributes<I>, I>(tag, {...props,...this._elementProps});
        }else{
          return createElement<React.HTMLAttributes<I>, I>(tag, props);
        }
      }

**Comment by augustjk** [comment] 2023-05-01 17:24
@ChellappanRajan Yes this is what solution 1 in the original post might look like. I think we want to consider a more sophisticated approach as described with solution 2 though.

Implementing either solution also will likely cause hydration warnings as described in https://github.com/lit/lit/issues/3858 as well. I think hydration warnings are preferable to the unwanted rendering with default prop. Addressing that without a blanket `suppressHydrationWarning` means we'd need to also consider passing through some props during client rendering as well, particularly if the prop is meant to reflect to attribute.

We're looking to huddle on this soon.

**Comment by ChellappanRajan** [comment] 2023-05-01 17:44
Thanks @augustjk 

Since the extra props warning will be skipped in the production build as a workaround, should I use this temporary solution until this issue is fixed in the main branch?

**Comment by augustjk** [comment] 2023-05-01 17:51
@ChellappanRajan Yes, that sounds okay to me.

**Comment by augustjk** [comment] 2023-05-03 00:46
After doing a team huddle on this offline, we're going with the solution of adding `defer-hydration` to the host element during SSR so that we can imperatively add all the initial props onto the element before we remove the attribute to cause the initial update/hydration of the component to happen. This is the same approach we do for nested Lit components being SSRed and hydrated, making sure they receive initial props from parent components before doing their first update on the client.

As discussed here https://github.com/lit/lit/issues/3858#issuecomment-1532306195, we'd need to add `suppressHydrationWarning` to the host elements client side for this to not emit warnings, which we consider to be harmless.

There's a bit of question as to whether we should do this at the `@lit-labs/ssr-react` package to cover even non-wrapped components, or at the `@lit-labs/react` wrapper as it's only been affecting wrapped components due to the missing initial data.

Doing it in `@lit-labs/ssr-react` will have the advantage of non-wrapped components being able to work better with props that are not easily serializable. But we'd need to consider its interaction with the wrapper. As it is, the wrapper would never pass any of the props to the host element so the wrapper would need to be aware that it's being used in conjunction with `@lit-labs/ssr-react` and handle some props differently if that is the case.

**Comment by justinfagnani** [comment] 2023-05-03 17:46
Adding the `defer-hydration` is something we really should do in ssr-react anyway, since you get incorrect component initialization without it if any non-attribute properties were passed from React.

**Comment by augustjk** [comment] 2023-05-04 23:57
I need to better document the whole design and rationale somewhere, but in a nutshell, we want WCs to behave similarly with both SSR and client rendering.

Without wrappers, `ssr-react` will set all JSX props as attributes (as React does on the client) and do its best. Hydration will rely on initial data from these attributes. This should work fine for simple components where props can easily be represented as attributes, but not for complex components with non-serializable data or different attr/property name. They're currently not supported on the client right now so we won't support "proper" SSR & hydration of those without wrappers. (We'll have to see how this changes when WC support lands in React.)

With wrappers, in the server the wrapper will be aware if `ssr-react` is loaded, determine which JSX props should be attrs and which should be properties, and pass this along to the patched `createElement()`, with properties in a special prop (`__litProps__` maybe). `ssr-react` will only set properties for `__litProps__` and set attribute for other props during SSR, and also add `defer-hydration` to the host element. On the client, the wrapper on mount will set properties on the host element, then remove `defer-hydration` to then let it hydrate with all the correct properties set.

**Closed** 2023-05-16 22:59 UTC
