### ISSUE TITLE
[labs/virtualizer] Could ResizeObserver loop limit exceeded be caught

### ISSUE THREAD

**Issue by akc42** [lit/lit#3620] opened 2023-01-30 15:41 UTC
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

Virtualizer (@lit-labs/virtualizer)

### Description

I have started getting frequent `ResizeObserver loop limit exceeded` error occur from the Virtualiser.  According to all mentions of this around the internet it is benign and is for information purposes only.

I am using in the Virtualiser in a complex environment in which I have an "error" module to collect all unhandled errors and decide how to handle them (normally log them to the server).  It would be nice if the Virtualizer could catch them and suppress them it self

### Alternatives and Workarounds

I have added the following code in my error module,

```
    if(winerror.message === 'ResizeObserver loop completed with undelivered notifications.' || 
      winerror.message === 'ResizeObserver loop limit exceeded') {
        winerror.stopImmediatePropagation();
        return;
    }
```

**Comment by usergenic** [comment] 2023-02-10 06:19
I am definitely in favor of finding a way for Virtualizer to swallow the ResizeObserver loop limit exceeded cases which were caused by observers it constructed.  I agree this error case is super annoying; in particular we have to catch these errors in our test environment so the test runner doesn't consider them failures.  I'm not crazy about having virtualizer, by default, provide a window.onerror advice/wrapper, which is the only way I know of to get at these at the moment.

Maybe I should make an npm package called "ignore-resizeobserver-loop-limit-exceeded" that does that and only that.

The best outcome would be to figure out if there isn't *something* that can be addressed in the logic of the way virtualizer uses/reacts to ResizeObserver callbacks that could avoid the kind of queueing/cascading events that exceed the limit in the first place.  I haven't dedicated much time to digging through that problem yet, but I am not convinced it isn't worth doing.

**Comment by usergenic** [comment] 2023-02-10 06:22
FWIW this is how we address them in our Virtualizer tests

The helper method to ignore them:
https://github.com/lit/lit/blob/main/packages/labs/virtualizer/src/test/helpers.ts#L152

How this is used in the test's describe block:
https://github.com/lit/lit/blob/main/packages/labs/virtualizer/src/test/scenarios/range-changed-events.test.ts#L19

**Comment by akc42** [comment] 2023-02-10 06:30
I trap the errors in my error handling custom element, but one has to wonder why the spec is like it is. Why could't a bubbling error be thrown on the element that the resizeObserver is observing.

**Comment by usergenic** [comment] 2023-02-10 06:48
@akc42 if you come upon a way to trap these ResizeObserver loop limit exceeded errors without hooking window.onerror, I'd be all over it!

**Comment by akc42** [comment] 2023-02-10 07:12
@usergenic No, I just have a standard window.onerror in a custom element I have at the top of my app to collect all errors and either use the Notification Api to inform the user that something went wrong and an api call to log it on the server. I just look for the text in the message and ignore those errors.  Real pain.  

As I said - why is the spec like it is!  We can't be the only ones suffering this pain.

**Comment by hlmitchell** [comment] 2023-03-09 23:48
Is there any progress on this? I can't use the window.onerror workaround and I'm being pushed to eliminate this error.

**Comment by usergenic** [comment] 2023-03-10 21:19
@hlmitchell the only way to swallow the errors at the moment are to make changes to window.onerror -- I can provide a convenience method to do so as part of virtualizer or as part of another package, but it's currently the only solution, barring some kind of logic changes to limit observer callbacks-- which I'm actually still interested in making work or ruling out.

Just to understand the nature of the limitation-- what is the reason you're not able to use the window.onerror workaround? I want to understand if a solution that depended on wrapping window.onerror would still not solve your use case.

**Comment by hlmitchell** [comment] 2023-03-13 15:47
It all comes down to getting my PR approved. So if the override is in the virtualizer package (or a different package), that likely wouldn't be an issue.

**Comment by usergenic** [comment] 2023-03-14 21:25
Okay I should have it a method for it in the next patch release.  We are still getting trying to usher the next batch of package releases in the lit monorepo right now, which will lead to virtualizer 2.0.0 and then I should have the error suppression by 2.0.1

**Comment by usergenic** [comment] 2023-04-08 00:33
Wanted to clarify that there are 3 scenarios here as I am adding support methods to suppress this annoying error.  The scenario that has mattered the most generally has been in testing environments (such as Mocha) which uses window.onerror to handle uncaught exceptions and treat them as test failures by default.

1. If the environment has an `window.onerror` handler, it needs to be wrapped/advised, i.e. replaced and then having the original called for all other errors.
2. If the environment does NOT currently have a `window.onerror` defined, it may be sufficient to add a handler via `window.addEventListener('error', () => {match error text} && event.preventDefault())` to suppress the errors.
3. If the window has a pre-existing `window.addEventListener('error')` registered, there's not really a standard way to wrap/advise an existing registered handlers.

**Comment by usergenic** [comment] 2023-05-31 17:25
#3929 should resolve the #1 case and provides a solution for #2

**Comment by usergenic** [comment] 2023-06-28 21:20
@akc42 let me know if these functions added helped you out.  I'll be looking at ways to reduce the cascade of observer callbacks architecture-wise following an upcoming big refactor that relates to handling writing-mode and direction.  For now will be closing this issue since there is no way to "catch" these errors beyond what I've added in #3929

**Closed by usergenic** 2023-06-28 21:20 UTC

**Comment by akc42** [comment] 2023-06-29 06:08
@usergenic Thanks for your work on this.  However for me personally it didn't meed a solution as I had direct control of the error handler and just dealt with it there.  I think it was others who needed it.

My main issue was (and still is) that I think its a badly defined specification and wondered maybe if your contacts could be used to directly question that and perhaps influence it being changed.

I also, in the end wrote my own virualiser element (205 lines of code, including comments) as this one was far to much of an overkill for what I needed.
