### ISSUE TITLE
[@lit-labs/virtualizer] TypeError: Cannot set property 'totalItems' of undefined

### ISSUE THREAD

**Issue by herberthobregon** [lit/lit#1965] opened 2021-06-18 08:25 UTC
# Description

Can update from lit-virtualizer to @lit-labs/virtualizer because have this error:  `TypeError: Cannot set property 'totalItems' of undefined in VirtualScroller.js`

# Steps to Reproduce

1. Write this code

```ts
import {html, css, LitElement} from 'lit';
import {customElement, property} from 'lit/decorators.js';
import '@lit-labs/virtualizer';

@customElement('my-list')
export class MyList extends LitElement {
    @property({ type: Array }) items: any[] = [1,2,3,4,5];

    render() {
        return html`
            <h1>list:</h1>
            <lit-virtualizer .items=${this.items || []} .renderItem=${(item: any) => html`<div>${item}</div>`}> 
            </lit-virtualizer>
        `;
    }
}
```

2. See this output...

```
VirtualScroller.js:418 Uncaught (in promise) TypeError: Cannot set property 'totalItems' of undefined
    at VirtualScroller._updateLayout (VirtualScroller.js:418)
    at VirtualScroller._schedule (VirtualScroller.js:389)
```
## Live Reproduction Link

https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgcHJvcGVydHl9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcbmltcG9ydCAnQGxpdC1sYWJzL3ZpcnR1YWxpemVyJztcblxuQGN1c3RvbUVsZW1lbnQoJ215LWxpc3QnKVxuZXhwb3J0IGNsYXNzIE15TGlzdCBleHRlbmRzIExpdEVsZW1lbnQge1xuICAgIEBwcm9wZXJ0eSh7IHR5cGU6IEFycmF5IH0pIGl0ZW1zOiBhbnlbXSA9IFsxLDIsMyw0LDVdO1xuXG4gICAgcmVuZGVyKCkge1xuICAgICAgICByZXR1cm4gaHRtbGBcbiAgICAgICAgICAgIDxoMT5saXN0OjwvaDE-XG4gICAgICAgICAgICA8bGl0LXZpcnR1YWxpemVyIC5pdGVtcz0ke3RoaXMuaXRlbXMgfHwgW119IC5yZW5kZXJJdGVtPSR7KGl0ZW06IGFueSkgPT4gaHRtbGA8ZGl2PiR7aXRlbX08L2Rpdj5gfT4gXG4gICAgICAgICAgICA8L2xpdC12aXJ0dWFsaXplcj5cbiAgICAgICAgYDtcbiAgICB9XG59XG5cbiJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9zaW1wbGUtZ3JlZXRpbmcuanNcIj48L3NjcmlwdD5cbjwvaGVhZD5cbjxib2R5PlxuICA8bXktbGlzdD48L215LWxpc3Q-XG48L2JvZHk-XG4ifV0

## Actual Results

Console error.
```
VirtualScroller.js:418 Uncaught (in promise) TypeError: Cannot set property 'totalItems' of undefined
    at VirtualScroller._updateLayout (VirtualScroller.js:418)
    at VirtualScroller._schedule (VirtualScroller.js:389)
```

## Browsers Affected

- [x] Chrome 91

**Comment by aricardoguzman** [comment] 2021-07-26 01:09
Same issue here, any update?

**Comment by nhayashida** [comment] 2021-08-18 09:58
I think this can be the workaround
https://github.com/PolymerLabs/uni-virtualizer/issues/103#issuecomment-875580352

**Comment by herberthobregon** [comment] 2021-09-16 08:12
@graynorton do you have any idea of this error?

**Comment by graynorton** [comment] 2022-01-14 23:44
Duplicate of https://github.com/PolymerLabs/uni-virtualizer/issues/103

**Closed by graynorton** 2022-01-14 23:44 UTC
