### ISSUE TITLE
[labs/nextjs] Support for the `app` directory

### ISSUE THREAD

**Issue by augustjk** [lit/lit#3657] opened 2023-02-08 01:39 UTC
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

Other/unknown (please mention in description)

### Description

Next.js v13 introduced the `app` directory, an alternative to the existing `pages` directory. https://nextjs.org/blog/next-13#new-app-directory-beta

This feature is considered beta and not recommended for production at this time.

The current implementation of the Lit SSR plugin for Next.js won't work for users using this as we're looking specifically for the `pages` directory for the entry points.

Supporting this may be as simple as adding to the test regex but will require testing.

### Alternatives and Workarounds

.

**Comment by ericis** [comment] 2023-05-15 21:10
@augustjk et al, this is no longer marked as `experimental` in the NextJS configuration when using "create-next-app".
https://github.com/vercel/next.js/blob/a7601213ab1bd2fd75e120907cd7c70278d7ebc7/packages/create-next-app/templates/app/js/next.config.js#L2

```js
/** @type {import('next').NextConfig} */
const nextConfig = {}

module.exports = nextConfig
```

The "old" way used to look like:

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    appDir: true,
  },
}

module.exports = nextConfig
```

**Comment by augustjk** [comment] 2023-06-20 21:08
`app` directory support definitely looks worthwhile to pursue. It does appear that something with the App router breaks Declarative Shadow DOM parsing even for browsers that should support it, so it won't be as simple as updating the entrypoint regex.

I'll investigate and add updates here.

**Comment by augustjk** [comment] 2023-08-04 17:31
@datradito sorry I haven't gotten around to investigating fully yet as we've been focused on other things for the Lit 3.0 release. I can't say for sure when I'll get to it but it's high on my list of things to do after 3.0.

**Comment by ChellappanRajan** [comment] 2023-09-08 13:31
Hi @augustjk, when we consume the @labs/react wrapped web component in a Next.js application and use the app router, we encounter this error. Do you think this could be due to the app's layout?

![image](https://github.com/lit/lit/assets/22997191/63cba807-6ce9-4520-8059-14095d0a6bcd)

**Comment by steveworkman** [comment] 2023-10-03 21:06
There's a lot of [really good investigation in to this from @ceIia & others on Discord](https://discord.com/channels/1012791295170859069/1138460266376474726). In short:
- Reproduction: https://github.com/ceIia/lit-next-ssr
- `"use client"` makes the error go away, but switches to CSR
- simple bare lit elements _should render_ in RSCs but a lot of them behave more like client components so `use client` is a valid solution
- another solution is an alternative wrapper like `createComponent` that works without React hooks, which would then work in RSC

In addition, for component library authors you can add `use client` to all your components as part of the build process like this https://github.com/shuding/react-wrap-balancer/blob/main/tsup.config.ts#L10-L13

I bring this up again as I got caught out when creating a new nextjs app and going for the **recommended** options, which now don't work without `use client`

<img width="738" alt="image" src="https://github.com/lit/lit/assets/994905/e55230ef-3fdd-4b92-af0a-42e6fa44fff1">

I also played around with bare imports for a simple component and with `@lit-labs/nextjs@0.1.2` and `@lit/react@1.0.0-pre`
I was able to see a server render for the component, but it then fell into hydration issues described in https://github.com/lit/lit/issues/3858 even when matching the reflected attributes correctly.

**Comment by ceIia** [comment] 2023-11-07 20:22
hey! a new issue popped up with the latest version of next (14.0.1):

this issue breaks the build both with importing the `enable-lit-ssr.js` script from @lit-labs/ssr-react or the `withLitSSR()` from @lit-labs/nextjs config:

```
Error occurred prerendering page "/test/98". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot set property createElement of [object Module] which has only a getter
    at 9485 (/Users/celiabourial/.dev/lit-next-ssr/.next/server/chunks/392.js:48:19)
    at __webpack_require__ (/Users/celiabourial/.dev/lit-next-ssr/.next/server/webpack-runtime.js:1:145)
    at 6823 (/Users/celiabourial/.dev/lit-next-ssr/.next/server/chunks/850.js:1:474)
    at __webpack_require__ (/Users/celiabourial/.dev/lit-next-ssr/.next/server/webpack-runtime.js:1:145)
    at F (/Users/celiabourial/.dev/lit-next-ssr/node_modules/.pnpm/next@14.0.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:36:6049)
    at $ (/Users/celiabourial/.dev/lit-next-ssr/node_modules/.pnpm/next@14.0.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:36:4600)
    at rS (/Users/celiabourial/.dev/lit-next-ssr/node_modules/.pnpm/next@14.0.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:28:27173)
    at nC (/Users/celiabourial/.dev/lit-next-ssr/node_modules/.pnpm/next@14.0.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:28:52685)
    at nR (/Users/celiabourial/.dev/lit-next-ssr/node_modules/.pnpm/next@14.0.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:28:57452)
    at nk (/Users/celiabourial/.dev/lit-next-ssr/node_modules/.pnpm/next@14.0.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:28:49214)
```

i just tried next@13.5.6 and it builds fine, but with 14.0.1 doesn't (i haven't checked which canary between those two versions breaks it yet though).
i've updated my repro of the original issue repo on a separate branch linked below. 

→ https://github.com/ceIia/lit-next-ssr/tree/next-14

**Comment by augustjk** [comment] 2023-11-07 21:22
Oof.. it seems maybe they're doing es modules so monkey patching `React.createElement` doesn't work.

**Comment by ceIia** [comment] 2023-11-08 10:09
update: next.js version [13.4.20-canary.31](https://www.npmjs.com/package/next/v/13.4.20-canary.31) is the last version to work. upwards of canary.32 included, the bug above appears.

**Comment by augustjk** [comment] 2023-11-21 06:17
I found a discussion in the nextjs repo regarding declarative shadow dom and posted a comment there. https://github.com/vercel/next.js/discussions/51717#discussioncomment-7626566

For now, I think we just won't be able to have custom elements being server rendered with DSD within a React Server Component. Since RSC only get rendered on the server, never client-side, it also means that component definitions won't get shipped if that's the only place it is used. 

I tried a home page without any custom elements, that links to another page that does contain a custom element. The way Next.js handles the client routing is to make an API call to the server which returns the serialized server tree including the RSC. This means the tree with the template element that has a prop called "shadowrootmode" which is re-created client side by Next/React. Of course the browser does not treat this as DSD. The custom element won't even client render because code used in RSC is not shipped to the client and it doesn't "hydrate".

To use custom elements with the App router in Next.js, I think the only solution for now is to use them in React client components with the `'use client';` directive. I have checked that that actually does SSR for initial page requests, and hydrates properly. Navigating to other pages that have the custom element in a client component also seems to work.

**Comment by augustjk** [comment] 2023-11-21 06:20
Something we can do for now would be update the regex used in the plugin for the injection point to allow app folder structure, and document that custom elements to be server rendered should only be used in React client components.

We also need to figure out what's going on with the module situation in Next.js 14. I think that's a separate issue though.

**Comment by Roman86** [comment] 2024-02-09 13:09
up =) any luck with this?

**Comment by gaearon** [comment] 2024-02-12 03:24
Left a small comment here: https://github.com/vercel/next.js/discussions/51717#discussioncomment-8437036

**Closed** 2024-04-24 05:55 UTC
