### ISSUE TITLE
allow unescaped JSON in html` templates

### ISSUE THREAD

**Issue by dellfort** [lit/lit#4713] opened 2024-07-25 05:34 UTC
### Which package(s) are affected?

SSR (@lit-labs/ssr)

### Description

When I want to use an importmap in my html template the JSON quots are being escaped.

current behaviour:
I have to unescape the resulting string to have plain JSON in HTML.

expected behaviour: 
${JSON.stringify(importmap)} in html` just works.

### Reproduction

```
import { importmap } from '../assets/libs/importmap.js'

export async function renderIndexHTML(baseUrl: string) {

  const template: TemplateResult = html`
    <!DOCTYPE html>
    <html lang="${language}">
      <head>
        <meta charset="UTF-8">
        <base href="${baseUrl}">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="Content-Security-Policy" content="style-src 'self'">
        <script type="importmap">${JSON.stringify(importmap)}</script>       
        <script type="module" src="./libs/@lib/index.js“></script>  
      </head>
      <body></body>
    </html>
  `;

  const result: RenderResult = render(template);
  const collectedRes: string = collectResultSync(result)
  
  // need to unescape stringified import map JSON:
  const collectedResUnescaped = collectedRes.replace(/&quot;/g, '"')

  return collectedResUnescaped
}

```

### Workaround

The workaround I am using ist to unescape the resulting strings, which of course could lead to unwanted side effects:
const collectedResUnescaped = collectedRes.replace(/&quot;/g, '"')

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

@lit-labs/ssr 3.2.2"

### Browser/OS/Node environment

Node.js v18.20.2

**Comment by justinfagnani** [comment] 2024-09-06 17:12
lit-html on the client doesn't escape or unescape any strings passed to bindings. It only passes the data directly to `textNode.data`. Lit SSR escapes bindings to match the client behavior.

The `unsafeHTML()` directive is how we typically get around escaping issues. I think that'll work in the importmap case as well.

**Comment by justinfagnani** [comment] 2024-10-02 01:17
I'm going to close this as working as intended. We can't allow unescaped values into bindings by default for security reasons.

**Closed by justinfagnani** 2024-10-02 01:17 UTC
