### ISSUE TITLE
ERROR in ./node_modules/@lit-labs/motion/index.js - Can't resolve './flip-controller.js'

### ISSUE THREAD

**Issue by herberthobregon** [lit/lit#1807] opened 2021-04-24 01:34 UTC
# Description

Missing *.d.ts in @lit-labs

incorrect import, remove all *.js in import of /packages/labs/motion/src/flip.ts

# Steps to Reproduce

1. Write this code

```ts
import {flip} from '@lit-labs/motion';

class MyElement extends LitElement {
  render() {
    return html`
      <button @click=${this._toggle}>Move</button>
      <div class="box" ${flip()}></div>
    `;
  }
}
```

## Expected Results

Correct import

## Actual Results

Module not found: Error: Can't resolve './flip-controller.js' in @lit-labs/motion

**Comment by justinfagnani** [comment] 2021-04-24 03:45
Thanks for the report. This is a duplicate of #1796. That's fixed on main and will be released soon.

**Closed by justinfagnani** 2021-04-24 03:45 UTC
