### ISSUE TITLE
[@lit-labs/react] attributes not set in `connectedCallback`

### ISSUE THREAD

**Issue by sbolz** [lit/lit#2694] opened 2022-04-01 09:20 UTC
# Description

When wrapping a custom Element with @lit-labs/react's `createComponent`, the initial rendering of the component will just render the tag itself to the DOM, without any attributes set.

# Steps to Reproduce

@e111077 was so kind to provide an example [codesandbox](https://codesandbox.io/s/cool-carlos-q3jfly?file=/src/App.js).

Example:
Say I have a component `my-component` that has the following connectedCallback:
```
    connectedCallback() {
      console.log("name attribute:", this.getAttribute("name"));
    }
```

Then the natively rendered web-component will correctly log the `name` attribute:
```jsx
<my-component name="hello"></my-component> // will log "name attribute: hello"
```
while the React component will log `null`:

```jsx
<MyComponent name="hello"></MyComponent>  // will log "name attribute: null"
```

**Comment by taylor-vann** [comment] 2022-04-04 18:25
@sbolz thanks for submitting! 

The null / undefined value is an artifact of React's rendering process.
The example provided provides the following output
```
constructor undefined
connected undefined
connected asdf
```

AFAICT during the `pragma` transformation, `my-component` will be instantiated without any props (constructor logs `undefined`). Then it will be attatched to the DOM without any props (connected logs `undefined` again). However, react will at any time obliterate the DOM in favor of state (hence another connected logs `adsf`)

Basically this is working as intended, the example eventually resolves into the correct state after react has its say.

**Comment by taylor-vann** [comment] 2022-04-04 18:26
closing for now! feel free to reopen if properties do not eventually resolve during the react render process.

**Closed by taylor-vann** 2022-04-04 18:26 UTC

**Comment by sbolz** [comment] 2022-04-05 05:40
Thanks for the explanation :)

**Comment by husseinraoouf** [comment] 2023-06-30 12:44
@taylor-vann i think your explanation make sense, but still we need to be able initialize the component with `attributes` from the start, maybe delay
