### ISSUE TITLE
Child doesn't re-render when parent updates property

### ISSUE THREAD

**Issue by Naxus28** [lit/lit#4651] opened 2024-05-23 19:17 UTC
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

**Description**: I am updating the "variant" property in parent component within an event listener. I checked that the property is indeed being updated in the parent both through a console.log in the render method and in the browser "properties" tab when the event is dispatched. I also checked that the child component's property is updated in the browser "properties". However, that update is not triggering a re-render of the child component. I have worked on different components before and this functionality worked seamlessly but for some reason it is not working now. 

**Expected outcome**: the child component should re-render and change the UI to reflect the updated property.

**Actual outcome**: the child is not re-rendered

### Reproduction

**Parent component**
```
import { css, html, LitElement } from 'lit'
import { customElement, property } from 'lit/decorators.js'

@customElement('my-widget')
export default class MyButtonWidget extends LitElement {
 static shadowRootOptions: ShadowRootInit = { mode: 'closed' } // tried with "mode" open as well
  static styles = css`
    :host {
      display: block;
    }
  `

  @property({ attribute: 'buttonid', type: String })
  buttonId = ''

  @property({ type: String })
  clickEventId = ''

  @property({ type: String })
  iconSrc = ''

  @property({ type: String })
  iconPosition: 'left' | 'right' = 'right'

  @property({ type: String })
  styleOverrides: StyleOverrides = {}

  @property({ type: String })
  text = ''

 // this property
  @property({ type: String })
  variant?: ButtonVariants

  connectedCallback() {
    super.connectedCallback()
    document.addEventListener(this.clickEventId, (e) => this.onClickHandler(e) as unknown as EventListener)
    document.addEventListener(
      modalCloseEventName,
      (e) => this.handleModalClose(e as CustomEvent) as unknown as EventListener
    )
  }

  disconnectedCallback() {
    super.disconnectedCallback()
    document.removeEventListener(this.clickEventId, this.onClickHandler as EventListener)
    document.removeEventListener(modalCloseEventName, this.handleModalClose as unknown as EventListener)
  }

 async handleModalClose(e: CustomEvent<{ buttonId: string; actionType: ButtonVariants }>) {
    if (e.detail.buttonId !== this.buttonId) return
    this.variant = e.detail.actionType // e.detail.actionType is "completed"
    this.requestUpdate()
  }

  onClickHandler(e: Event) {
    e.stopPropagation()
    // handle child button click here 
    }
  }

  render() {
    return html`
      <my-button
        eventId=${this.clickEventId}
        iconSrc=${this.iconSrc}
        .styleOverrides=${this.styleOverrides}
        text=${this.text}
        variant=${this.variant}
      ></my-button>
    `
  }
}
```

**Child component**
```
import { html, LitElement, PropertyValues } from 'lit'
import { customElement, property } from 'lit/decorators.js'
import { classMap } from 'lit/directives/class-map.js'
import { styleMap } from 'lit/directives/style-map.js'

import { ButtonVariants } from '../../shared/widget-models/button-widget.models'

import * as styles from 'bundle-text:./styles/styles.scss'

const styleSheet = new CSSStyleSheet()

try {
  styleSheet.replaceSync(styles)
} catch (e) {}

@customElement('my-button')
export default class MyButton extends LitElement {
  static shadowRootOptions: ShadowRootInit = { mode: 'closed' } // tried with "mode" open as well
  static styles = [styleSheet]

  @property({ type: String })
  eventId = ''

  @property({ type: String })
  iconPosition: 'left' | 'right' = 'right'

  @property({ attribute: true, type: String })
  iconSrc = ''

  @property({ type: Object })
  styleOverrides = {}

  @property({ attribute: true, type: String })
  text = ''

 // never updated
  @property({ type: String })
  variant?: ButtonVariants

// never called
 protected updated(_changedProperties: PropertyValues): void {
    console.log('_changedProperties', _changedProperties)
  }

  onClick(e: Event) {
    document.dispatchEvent(
      new CustomEvent(this.eventId, {
        detail: { buttonText: this.text, originalEvent: e },
        bubbles: true,
        composed: true
      })
    )
  }


  render() {
    console.log('this.variant child', this.variant) // TODO: this is not updating--fix it
    return html`
      <button
        class=${classMap({
          'button': true,
          'button--icon-left': this.iconPosition === 'left'
        })}
        style="${styleMap(this.styleOverrides)}"
        @click="${this.onClick}"
        part="button-container"
      >
        <span class="button__text" part="button-text">${this.text}</span>
        <span class="button__icon-container">
          <img class="button__icon" part="button-icon" src=${this.iconSrc} />
          // this icon is never displayed
          ${this.variant === 'completed'
            ? html`<img
                class="button__checkmark-icon"
                part="button-checkmark-icon"
                src="https://my-icon.png"
              />`
            : ''}
        </span>
      </button>
    `
  }
}
```

### Workaround

I am dispatching an event from within `handleModalClose` and listening for that event in the child button component to then update the value of `variant`. This is not how this should work though so this is just a temporary patch to test the component.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

 "lit": "^3.1.3"

### Browser/OS/Node environment

Browser:  Chrome Version 124.0.6367.209, OS: MacOS 14.5 (23F79), Node version: v19.3.0, NPM version: 9.2.0

**Comment by augustjk** [comment] 2024-05-23 22:00
Nothing from the code here looks wrong with regards to the properties. If you're certain the property is set on the child component via inspecting with the browser dev tool, maybe you're looking at the source code for a different child component. Is the correct component definition being registered?

If you're not able to provide a running reproduction, I can't say what else could be the problem here.

Side note, the event listener cleanup in your parent's `disconnectedCallback()` won't work as when the event listeners are added, they're anonymous arrow functions. You need to provide the same reference of those functions to clean them up, or [use an abort signal to remove those](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#signal).

**Comment by Naxus28** [comment] 2024-05-23 22:44
Thanks for the prompt response. I am looking at the correct components on the browser though. Here you can see that the attribute is changed on the markup after the "variant" property is updated in the parent (copied from the browser--changed actual component names):

```
<my-widget buttonid="3f73b6b0-1954-11ef-9181-0da43c3989ff" class="my-button">
   <my-button clickeventid="my-button-click" 
     iconsrc="icon.png" text="Button Text set from parent" 
     variant="completed"> // here is the updated attribute value--this is reflected in the browser property but not in the component property
          <button part="button-container" class="button" style="background:#000000;font-family:Helvetica;">
        <span class="button__text" part="button-text"><!--?lit$8478536446$-->Button Text set from parent</span>
        <span class="button__icon-container">
          <img class="button__icon" part="button-icon" src="icon.png>
         // the other img tag should have been rendered here if the  "variant" property had been updated
          <!--?lit$8478536446$-->0
        </span>1
      </button>

     </my-button>

</my-button-widget>
```

My company blocks code sandboxes so it is difficult to create a reproducible. I will take a look around though. In the mean time, does this help at all?

**Comment by augustjk** [comment] 2024-05-23 23:29
That all looks fine.. It really shouldn't matter but you might try doing a property binding in the parent's render `<my-button .variant=${this.variant}>`.

**Comment by sorvell** [comment] 2024-05-24 00:14
If the child's attribute is set correctly, but it's not rendering, then the problem is with the child component. On the child:
1. verify that the property `.variant` is correctly set.
2. try setting it with the inspector: inspect the child and in the console execute `$0.variant = 'completed'`

If the `variant` property is not being set or not provoking an update, then either it did not change or it is not properly setup as a reactive property.

**Comment by Naxus28** [comment] 2024-05-24 02:20
@augustjk i tried that already. Same result.

**Comment by Naxus28** [comment] 2024-05-24 02:33
@sorvell this is how I am setting up the property in the child:

```
 @property({ type: String })
  variant?: ButtonVariants
  ```

I tried`$0.variant = 'completed'`, but the variable was not set in the component though when I log `$0.variant` it is now "completed". However, I also tried to set another reactive property that is currently being set correctly from the parent ("text") and that variable also didn't update via the browser method.

**Comment by Naxus28** [comment] 2024-05-24 03:50
I also noticed that though the parent re-renders with the updated variable value (I am logging the value in the render method) the “changedProperties” in the updated lifecycle method is an empty map. So even though the lifecycle runs it the map doesn’t have the “variant” variable. I tried to update other variables and the result is the same. It seems like the child is only rendering with the properties passed by the parent when the component first mounts.

**Comment by sorvell** [comment] 2024-05-24 12:09
> this is how I am setting up the property in the child

That's fine. I don't see the problem in the code that you posted. I think there's likely something about the child setup that's problematic. If you can make a playground example of the problem that'd be best and/or point us to a repo to see the actual code, if possible.

> I tried$0.variant = 'completed', but the variable was not set in the component though when I log $0.variant it is now "completed".

That's confusing since you say the value isn't set but then say the value is equal to the value you set. Do you mean the component didn't update?

**Comment by Naxus28** [comment] 2024-05-24 14:19
@sorvell yes, the component is not update. But the value is also not updated on the properties tab.

**Comment by sorvell** [comment] 2024-05-24 15:12
Again, based on the information provided, it sounds like the child properties are not properly setup to be reactive. There does not appear to be anything wrong with how you're defining them with the `@property` decorator, so there's some missing information.

1. Are you running in dev mode or production, and if dev mode, are there any console errors after the page loads?
2. What version of TypeScript are you using? (if it's >= 5 you would need to use `accessor` when defining properties).

If the problem persists, then to get more help you'll either need to make a reproduction or to provide more of the code of the child element.

**Comment by justinfagnani** [comment] 2024-05-24 15:14
> What version of TypeScript are you using? (if it's >= 5 you would need to use accessor when defining properties).

This is only true if not using `experimentalDecorators: true`

Another possible cause is `experimentalDecorators: true` but not `useDefineForClassFields: false`

**Comment by Naxus28** [comment] 2024-05-24 15:29
@sorvell:
1. no console errors
2. ` "typescript": "^3.9.5"`

@justinfagnani :
Using parcell to bundle the code, here is my `.babelrc`:
```
{
      presets: ['@babel/typescript'],
      plugins: [
        ['@babel/plugin-proposal-decorators', { legacy: true }],
        '@babel/plugin-proposal-class-properties',
        '@babel/plugin-proposal-object-rest-spread',
        '@babel/plugin-transform-private-methods'
      ]
    }
```

**Comment by Naxus28** [comment] 2024-05-24 15:31
@sorvell I created this playground but it is not rendering the button: https://lit.dev/playground/#project=W3sibmFtZSI6Im15LWJ1dHRvbi50cyIsImNvbnRlbnQiOiJpbXBvcnQgeyBodG1sLCBMaXRFbGVtZW50LCBQcm9wZXJ0eVZhbHVlcywgY3NzIH0gZnJvbSAnbGl0J1xuaW1wb3J0IHsgY3VzdG9tRWxlbWVudCwgcHJvcGVydHkgfSBmcm9tICdsaXQvZGVjb3JhdG9ycy5qcydcbmltcG9ydCB7IGNsYXNzTWFwIH0gZnJvbSAnbGl0L2RpcmVjdGl2ZXMvY2xhc3MtbWFwLmpzJ1xuaW1wb3J0IHsgc3R5bGVNYXAgfSBmcm9tICdsaXQvZGlyZWN0aXZlcy9zdHlsZS1tYXAuanMnXG5cbnR5cGUgQnV0dG9uVmFyaWFudHMgPSAnY29tcGxldGVkJyB8ICdpbi1wcm9ncmVzcycgfCAnZGVmYXVsdCdcblxuQGN1c3RvbUVsZW1lbnQoJ215LWJ1dHRvbicpXG5leHBvcnQgZGVmYXVsdCBjbGFzcyBNeUJ1dHRvbiBleHRlbmRzIExpdEVsZW1lbnQge1xuICBzdGF0aWMgc2hhZG93Um9vdE9wdGlvbnM6IFNoYWRvd1Jvb3RJbml0ID0geyBtb2RlOiAnY2xvc2VkJyB9IC8vIHRyaWVkIHdpdGggXCJtb2RlXCIgb3BlbiBhcyB3ZWxsXG4gIHN0YXRpYyBzdHlsZXMgPSBjc3NgXG4gICA6aG9zdCB7XG4gICAgIGJveC1zaXppbmc6IGJvcmRlci1ib3g7XG4gICAgIHdpZHRoOiAxMDAlO1xuICAgICBtaW4td2lkdGg6IDEyMHB4O1xuICAgICBoZWlnaHQ6IDcwcHg7XG4gICB9XG5cbiAgIC5teS1idXR0b24ge1xuICAgIGRpc3BsYXk6IGZsZXg7XG4gICAgYWxpZ24taXRlbXM6IGNlbnRlcjtcbiAgICBqdXN0aWZ5LWNvbnRlbnQ6IHNwYWNlLWJldHdlZW47XG4gICAgYm9yZGVyOiBub25lO1xuICAgIGJvcmRlci1yYWRpdXM6IDRweDtcbiAgICBiYWNrZ3JvdW5kOiBibGFjaztcbiAgICBjdXJzb3I6IHBvaW50ZXI7XG4gICAgcGFkZGluZy1yaWdodDogMTZweDtcbiAgICBwYWRkaW5nLWxlZnQ6IDE2cHg7XG4gICAgd2lkdGg6IDEwMCU7XG4gICAgaGVpZ2h0OiA2NHB4O1xuICAgIGNvbG9yOiB3aGl0ZTtcbiAgICBmb250LXdlaWdodDogNjAwO1xuICAgIGdhcDogOHB4O1xuICAgfVxuXG4gIC5teS1idXR0b25fX3RleHQge1xuICAgIGRpc3BsYXk6IGJsb2NrO1xuICAgIHRleHQtYWxpZ246IGxlZnQ7XG4gICAgbGluZS1oZWlnaHQ6IDMwcHg7XG4gICAgZm9udC1mYW1pbHk6IE9wdGltaXN0LCBJbnRlciwgQXJpYWwsIHNhbnMtc2VyaWY7XG4gICAgZm9udC1zaXplOiAxOHB4O1xuICB9XG5cbiAgLm15LWJ1dHRvbl9faWNvbi1jb250YWluZXIge1xuICAgIGRpc3BsYXk6IGZsZXg7XG4gICAgYWxpZ24taXRlbXM6IGNlbnRlcjtcbiAgICBnYXA6IDIwcHg7XG4gIH1cblxuICAubXktYnV0dG9uX19pY29uIHtcbiAgICBkaXNwbGF5OiBibG9jaztcbiAgICB3aWR0aDogMjRweDtcbiAgICBoZWlnaHQ6IDI0cHg7XG4gIH1cblxuICAubXktYnV0dG9uX19jaGVja21hcmstaWNvbiB7XG4gICAgZGlzcGxheTogYmxvY2s7XG4gICAgd2lkdGg6IDMwcHg7XG4gICAgaGVpZ2h0OiAzMHB4O1xuICB9XG5cbiAgLm15LWJ1dHRvbi0taWNvbi1sZWZ0IHtcbiAgICBmbGV4LWRpcmVjdGlvbjogcm93LXJldmVyc2U7XG4gIH1cbiAgYFxuXG4gIEBwcm9wZXJ0eSh7IHR5cGU6IFN0cmluZyB9KVxuICBldmVudElkID0gJydcblxuICBAcHJvcGVydHkoeyB0eXBlOiBTdHJpbmcgfSlcbiAgaWNvblBvc2l0aW9uOiAnbGVmdCcgfCAncmlnaHQnID0gJ3JpZ2h0J1xuXG4gIEBwcm9wZXJ0eSh7IGF0dHJpYnV0ZTogdHJ1ZSwgdHlwZTogU3RyaW5nIH0pXG4gIGljb25TcmMgPSAnJ1xuXG4gIEBwcm9wZXJ0eSh7IHR5cGU6IE9iamVjdCB9KVxuICBzdHlsZU92ZXJyaWRlcyA9IHt9XG5cbiAgQHByb3BlcnR5KHsgYXR0cmlidXRlOiB0cnVlLCB0eXBlOiBTdHJpbmcgfSlcbiAgdGV4dCA9ICcnXG5cbiAvLyBuZXZlciB1cGRhdGVkXG4gIEBwcm9wZXJ0eSh7IHR5cGU6IFN0cmluZyB9KVxuICB2YXJpYW50PzogQnV0dG9uVmFyaWFudHNcblxuLy8gbmV2ZXIgY2FsbGVkXG4gcHJvdGVjdGVkIHVwZGF0ZWQoX2NoYW5nZWRQcm9wZXJ0aWVzOiBQcm9wZXJ0eVZhbHVlcyk6IHZvaWQge1xuICAgIGNvbnNvbGUubG9nKCdfY2hhbmdlZFByb3BlcnRpZXMnLCBfY2hhbmdlZFByb3BlcnRpZXMpXG4gIH1cblxuICBvbkNsaWNrKGU6IEV2ZW50KSB7XG4gICAgZG9jdW1lbnQuZGlzcGF0Y2hFdmVudChcbiAgICAgIG5ldyBDdXN0b21FdmVudCh0aGlzLmV2ZW50SWQsIHtcbiAgICAgICAgZGV0YWlsOiB7IGJ1dHRvblRleHQ6IHRoaXMudGV4dCwgb3JpZ2luYWxFdmVudDogZSB9LFxuICAgICAgICBidWJibGVzOiB0cnVlLFxuICAgICAgICBjb21wb3NlZDogdHJ1ZVxuICAgICAgfSlcbiAgICApXG4gIH1cblxuXG4gIHJlbmRlcigpIHtcbiAgICByZXR1cm4gaHRtbGBcbiAgICAgIDxidXR0b25cbiAgICAgICAgY2xhc3M9JHtjbGFzc01hcCh7XG4gICAgICAgICAgJ2J1dHRvbic6IHRydWUsXG4gICAgICAgICAgJ2J1dHRvbi0taWNvbi1sZWZ0JzogdGhpcy5pY29uUG9zaXRpb24gPT09ICdsZWZ0J1xuICAgICAgICB9KX1cbiAgICAgICAgc3R5bGU9XCIke3N0eWxlTWFwKHRoaXMuc3R5bGVPdmVycmlkZXMpfVwiXG4gICAgICAgIEBjbGljaz1cIiR7dGhpcy5vbkNsaWNrfVwiXG4gICAgICAgIHBhcnQ9XCJidXR0b24tY29udGFpbmVyXCJcbiAgICAgID5cbiAgICAgICAgPHNwYW4gY2xhc3M9XCJidXR0b25fX3RleHRcIiBwYXJ0PVwiYnV0dG9uLXRleHRcIj4ke3RoaXMudGV4dH08L3NwYW4-XG4gICAgICAgIDxzcGFuIGNsYXNzPVwiYnV0dG9uX19pY29uLWNvbnRhaW5lclwiPlxuICAgICAgICAgIDxpbWcgY2xhc3M9XCJidXR0b25fX2ljb25cIiBwYXJ0PVwiYnV0dG9uLWljb25cIiBzcmM9JHt0aGlzLmljb25TcmN9IC8-XG4gICAgICAgICAgLy8gdGhpcyBpY29uIGlzIG5ldmVyIGRpc3BsYXllZFxuICAgICAgICAgICR7dGhpcy52YXJpYW50ID09PSAnY29tcGxldGVkJ1xuICAgICAgICAgICAgPyBodG1sYDxpbWdcbiAgICAgICAgICAgICAgICBjbGFzcz1cImJ1dHRvbl9fY2hlY2ttYXJrLWljb25cIlxuICAgICAgICAgICAgICAgIHBhcnQ9XCJidXR0b24tY2hlY2ttYXJrLWljb25cIlxuICAgICAgICAgICAgICAgIHNyYz1cImh0dHBzOi8vbXktaWNvbi5wbmdcIlxuICAgICAgICAgICAgICAvPmBcbiAgICAgICAgICAgIDogJyd9XG4gICAgICAgIDwvc3Bhbj5cbiAgICAgIDwvYnV0dG9uPlxuICAgIGBcbiAgfVxufSJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9teS13aWRnZXQuanNcIj48L3NjcmlwdD5cbjwvaGVhZD5cbjxib2R5PlxuICA8bXktd2lkZ2V0PjwvbXktd2lkZ2V0PlxuPC9ib2R5PlxuIn0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMi4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjQuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4zLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9LHsibmFtZSI6Im15LXdpZGdldC50cyIsImNvbnRlbnQiOiJpbXBvcnQgeyBjc3MsIGh0bWwsIExpdEVsZW1lbnQgfSBmcm9tICdsaXQnXG5pbXBvcnQgeyBjdXN0b21FbGVtZW50LCBwcm9wZXJ0eSB9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJ1xuaW1wb3J0ICcuL215LWJ1dHRvbi50cycgXG4gICAgXG50eXBlIEJ1dHRvblZhcmlhbnRzID0gJ2NvbXBsZXRlZCcgfCAnaW4tcHJvZ3Jlc3MnIHwgJ2RlZmF1bHQnXG5cbkBjdXN0b21FbGVtZW50KCdteS13aWRnZXQnKVxuZXhwb3J0IGRlZmF1bHQgY2xhc3MgTXlXaWRnZXQgZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiBzdGF0aWMgc2hhZG93Um9vdE9wdGlvbnM6IFNoYWRvd1Jvb3RJbml0ID0geyBtb2RlOiAnY2xvc2VkJyB9IFxuICBzdGF0aWMgc3R5bGVzID0gY3NzYFxuICAgIDpob3N0IHtcbiAgICAgIGRpc3BsYXk6IGJsb2NrO1xuICAgIH1cbiAgYFxuICBzdGF0aWMgcmVhZG9ubHkgbW9kYWxDbG9zZUV2ZW50TmFtZSA9ICdteUJ1dHRvbkNsb3NlTW9kYWwnXG4gICAgICBcbiAgQHByb3BlcnR5KHsgdHlwZTogU3RyaW5nIH0pXG4gIGNsaWNrRXZlbnRJZCA9ICdteS1jbGljay1ldmVudC1pZCdcbiAgICAgIFxuICBAcHJvcGVydHkoeyB0eXBlOiBTdHJpbmcgfSlcbiAgaWNvblNyYyA9ICdodHRwczovL2QzNTQ0bGExdThkanphLmNsb3VkZnJvbnQubmV0L0FQSEkvQmxvZy8yMDIxLzA3LTA2L3NtYWxsK3doaXRlK2ZsdWZmeStkb2crc21pbGluZythdCt0aGUrY2FtZXJhK2luK2Nsb3NlLXVwLW1pbi5qcGcnXG5cbiAgQHByb3BlcnR5KHsgdHlwZTogU3RyaW5nIH0pXG4gIGljb25Qb3NpdGlvbjogJ2xlZnQnIHwgJ3JpZ2h0JyA9ICdyaWdodCdcblxuICBAcHJvcGVydHkoeyB0eXBlOiBTdHJpbmcgfSlcbiAgdGV4dCA9ICdCdXR0b24gV2lkZ2V0J1xuXG4gIEBwcm9wZXJ0eSh7IHR5cGU6IFN0cmluZyB9KVxuICB2YXJpYW50PzogQnV0dG9uVmFyaWFudHMgPSAnZGVmYXVsdCdcblxuICBjb25uZWN0ZWRDYWxsYmFjaygpIHtcbiAgICBzdXBlci5jb25uZWN0ZWRDYWxsYmFjaygpXG4gICAgZG9jdW1lbnQuYWRkRXZlbnRMaXN0ZW5lcih0aGlzLmNsaWNrRXZlbnRJZCwgKGUpID0-IHRoaXMub25DbGlja0hhbmRsZXIoZSkgYXMgdW5rbm93biBhcyBFdmVudExpc3RlbmVyKVxuICAgIGRvY3VtZW50LmFkZEV2ZW50TGlzdGVuZXIoXG4gICAgICBNeVdpZGdldC5tb2RhbENsb3NlRXZlbnROYW1lLFxuICAgICAgKGUpID0-IHRoaXMuaGFuZGxlTW9kYWxDbG9zZShlIGFzIEN1c3RvbUV2ZW50KSBhcyB1bmtub3duIGFzIEV2ZW50TGlzdGVuZXJcbiAgICApXG4gIH1cblxuICBkaXNjb25uZWN0ZWRDYWxsYmFjaygpIHtcbiAgICBzdXBlci5kaXNjb25uZWN0ZWRDYWxsYmFjaygpXG4gICAgZG9jdW1lbnQucmVtb3ZlRXZlbnRMaXN0ZW5lcih0aGlzLmNsaWNrRXZlbnRJZCwgKGUpID0-IHRoaXMub25DbGlja0hhbmRsZXIoZSkgYXMgdW5rbm93biBhcyBFdmVudExpc3RlbmVyKVxuICAgIGRvY3VtZW50LnJlbW92ZUV2ZW50TGlzdGVuZXIoTXlXaWRnZXQubW9kYWxDbG9zZUV2ZW50TmFtZSwgKGUpID0-IHRoaXMuaGFuZGxlTW9kYWxDbG9zZShlIGFzIEN1c3RvbUV2ZW50KSBhcyB1bmtub3duIGFzIEV2ZW50TGlzdGVuZXIpXG4gIH1cblxuIGFzeW5jIGhhbmRsZU1vZGFsQ2xvc2UoZTogQ3VzdG9tRXZlbnQ8eyBhY3Rpb25UeXBlOiBCdXR0b25WYXJpYW50cyB9Pikge1xuICAgIHRoaXMudmFyaWFudCA9IGUuZGV0YWlsLmFjdGlvblR5cGUgXG4gICAgdGhpcy5yZXF1ZXN0VXBkYXRlKClcbiAgfVxuXG4gIG9uQ2xpY2tIYW5kbGVyKGU6IEV2ZW50KSB7XG4gICAgZS5zdG9wUHJvcGFnYXRpb24oKVxuICAgICAvLyBoYW5kbGUgY2xpY2tcbiAgfVxuXG4gIHJlbmRlcigpIHtcbiAgICByZXR1cm4gaHRtbGBcbiAgICAgIDxteS1idXR0b25cbiAgICAgICAgZXZlbnRJZD0ke3RoaXMuY2xpY2tFdmVudElkfVxuICAgICAgICBpY29uU3JjPSR7dGhpcy5pY29uU3JjfVxuICAgICAgICB0ZXh0PSR7dGhpcy50ZXh0fVxuICAgICAgICB2YXJpYW50PSR7dGhpcy52YXJpYW50fVxuICAgICAgPjwvbXktYnV0dG9uPlxuICAgIGBcbiAgfVxufSJ9XQ

**Comment by christophe-g** [comment] 2024-05-24 15:51
in `my-widget`:

  `import './my-button.js' ` instead of `import './my-button.ts' `

**Comment by Naxus28** [comment] 2024-05-24 16:07
@christophe-g thanks, the button is loading now. I am dispatching this event from the browser console but the event handler is not getting called:
```
document.dispatchEvent(
      new CustomEvent('myButtonCloseModal', {
        detail: { actionType: 'completed' },
        bubbles: true,
        composed: true
      })
    )
```

It does work though if I dispatch that same event from the button click in `my-button`

**Comment by sorvell** [comment] 2024-05-24 16:14
[Fixed example](https://lit.dev/playground/#gist=18c7243b538f65f51f33575c0125024a), it seems to work fine. I added an input that sets the variant from the parent and it's updating as expected.

I suspect the problem may be with the babel setup, and honestly that's challenging to help with. I would try compiling just with typescript at least for debugging, if possible.

**Comment by Naxus28** [comment] 2024-05-24 16:23
@sorvell it works when setting the variable directly in the parent but I need to set it via that handleModalClose event. What would be the reason for the failed update in that handler when the event is dispatched from outside the component tree?

**Comment by sorvell** [comment] 2024-05-24 16:28
> it works when setting the variable directly in the parent 

So this is new behavior? That doesn't seem to match what you were saying before.

> I need to set it via that handleModalClose event

Your code handles this event and the parent sets the variant based on it. So if setting from the parent works, then you need to verify the parent gets the event wiht the expected value.

**Comment by Naxus28** [comment] 2024-05-24 16:36
@sorvell this is what I need: the button click opens a modal that presents the user with a sequence of screens for specific flows. When the modal is closed—and if the user completes the steps—the button should display the check mark icon. So the parent button widget is listening for the modal close event. Once that event handler is invoked the state of the variant variable should change and update the child, which will then display the check mark icon. 

On the playground example, the child is displaying the check mark if:
1. The event is dispatched from the child itself on the button click, then the parent updates the variant state, and that state is passed back down to the child, which then displays the check mark. This was done just for testing. 
2. when the parent updates the state directly via that input that you added 

The child component doesn’t display the check mark icon when:
1. The event that triggers the update is dispatched from the browser console (and is imagine from a different component outside this component tree, which is what I need).

**Comment by Naxus28** [comment] 2024-05-24 16:44
@justinfagnani the current reproduction has the event failing as I described above. Just dispatch this event from the browser:
```
document.dispatchEvent(
      new CustomEvent('myButtonCloseModal', {
        detail: { actionType: 'completed' },
        bubbles: true,
        composed: true
      })
    )
    ```

The parent (`my-widget`) is listening for that event, and should update the variant variable when the handler (`handleModalClose`) is called but that doesn't happen.

If I remove the styles the button will look broken and make it more difficult to identify the failed behavior but I can try to reduce styles.

**Comment by sorvell** [comment] 2024-05-24 18:37
Then the problem is probably with the reactive properties defined on the child. Try the Babel related info above.

**Comment by Naxus28** [comment] 2024-05-24 22:02
@sorvell unfortunately that babel config broke my build. I am using a postMessage event now because I learned the modal will live in an iframe. Same result though but I started playing in the browser and overrode the code using the overrides option under the Sources tab to add console.logs and other checks to avoid rebundling the code for every change. When I first load the app (or refresh the window) and dispatch an event from the browser it doesn't work, no matter how many times I do it. 

However, ss soon as I edit the file on the browser (the overridden file), save, and dispatch the event again, the child finally updates. It kind of feels like something is not wired in properly on the first render but when the file is saved that problem is fixed. I am not really sure what to make of this.

**Comment by sorvell** [comment] 2024-05-25 13:33
Given what you've described, I think it's highly likely this is build related.  Unfortunately, decorators are not platform native yet so they require proper setup, and this can be finicky. The best supported path is building via TypeScript. While Babel is supported, it's trickier to setup since there are more options.

For debugging, you can try to avoid using decorators and seeing if it helps. Here's a basic example:


```js
import {html, css, LitElement} from 'lit';

export class SimpleGreeting extends LitElement {
  static properties = {
    name: {type: String},
  };

  constructor() {
    super();
    this.name = 'Somebody';
  }

  render() {
    return html`<p>Hello, ${this.name}!</p>`;
  }
}
customElements.define('simple-greeting', SimpleGreeting);

  
```

**Comment by Naxus28** [comment] 2024-05-27 00:13
@sorvell thanks, that was the issue. I finally got it to work by removing the decorators and using the static properties field. I had tried that before but I was also using class fields for those properties because typescript complains that the properties in the static property field don't exist in the class. This time around I removed the class fields and it worked. So now I am left with a lot of typescript warnings. Though they don't break the functionality the red squiggly lines all over the code are pretty annoying. I looked for an eslint rule to suppress the warnings per file but unfortunately didn't find one, except a global rule to ignore undefined variables, which I don't want. If you know how to remove the warnings I'd be happy to know, otherwise thanks a lot for the assistance!

**Comment by Naxus28** [comment] 2024-05-27 16:35
@sorvell this worked:

```
  @property()
  accessor foo = 'foo';
  ```

I had tried that before but typescript was not happy about the `accessor` keyword. This time around it didn't complain so I will take it. Thanks a lot!

**Comment by justinfagnani** [comment] 2024-05-27 16:47
It's helpful to be clear about which version of decorators you're actually compiling here.

If you're using the TypeScript compiler you could be using either experimental decorators or standard decorators. If you're using Babel (and Lit 3), you must use standard decorators.

Standard decorators must use the `accessor` keyword, but this is only supported by TypeScript 5 and up (and we really recommend 5.2 or later). Experimental decorators _can_ use the `accessor` keyword. If they don't though, the compiler settings should have `useDefineForClassFields: false` so that the compiler output doesn't define a property that shadows the accessors that the decorator creates.

**Comment by sorvell** [comment] 2024-05-29 23:39
Closing since this seems to be resolved.

**Closed by sorvell** 2024-05-29 23:39 UTC

**Comment by Naxus28** [comment] 2024-05-30 22:05
@sorvell thanks, the issue has been solved.
@justinfagnani this is the config:
```
// package.json
"typescript": "^3.9.5",
"lit": "^3.1.3",
"parcel": "^2.12.0",
"@parcel/babel-preset-env": "^2.12.0",

// tsconfig.json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "allowJs": true,
    "noEmit": true,
    "strict": true,
    "isolatedModules": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "useDefineForClassFields": false,
    "resolveJsonModule": true,
    "plugins": [
      {
        "name": "ts-lit-plugin",
        "strict": true
      }
    ]
  },
}

// .babelrc.js
{
      presets: ['@babel/typescript'],
      plugins: [
        ['@babel/plugin-proposal-decorators', { version: '2023-05' }],
        '@babel/plugin-transform-class-static-block',
        '@babel/plugin-proposal-class-properties',
        '@babel/plugin-proposal-object-rest-spread',
        '@babel/plugin-transform-private-methods'
      ]
    }

**Comment by Naxus28** [comment] 2024-05-30 22:06
@sorvell thanks, the issue has been solved.
@justinfagnani this is the config:
```
// package.json
"typescript": "^3.9.5",
"lit": "^3.1.3",
"parcel": "^2.12.0",
"@parcel/babel-preset-env": "^2.12.0",

// tsconfig.json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "allowJs": true,
    "noEmit": true,
    "strict": true,
    "isolatedModules": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "useDefineForClassFields": false,
    "resolveJsonModule": true,
    "plugins": [
      {
        "name": "ts-lit-plugin",
        "strict": true
      }
    ]
  },
}

// .babelrc.js
{
      presets: ['@babel/typescript'],
      plugins: [
        ['@babel/plugin-proposal-decorators', { version: '2023-05' }],
        '@babel/plugin-transform-class-static-block',
        '@babel/plugin-proposal-class-properties',
        '@babel/plugin-proposal-object-rest-spread',
        '@babel/plugin-transform-private-methods'
      ]
    }
