### ISSUE TITLE
Support for Preact when using @lit-labs/react

### ISSUE THREAD

**Issue by alshdavid** [lit/lit#2474] opened 2022-02-01 00:39 UTC
# Description

When using `@lit-labs/react` in a Preact project, we are unable to wrap the functionality of components.

# Steps to Reproduce

1. Write this code

```javascript
/** @jsx h */
import { LitElement } from 'lit';
import { createComponent } from '@lit-labs/react';
import { h, render } from 'preact';
import * as Preact from 'preact';

export class SimpleGreetingElement extends LitElement {
  render() {
    return html`<p>Hello World!</p>`;
  }
}

const SimpleGreeting = createComponent(
  Preact,
  'simple-greeting',
  SimpleGreetingElement
);

function App() {
  return (
    <div>
      <h1>Hello</h1>
      <SimpleGreeting />
    </div>
  );
}

render(<App />, document.body);
```

## Live Reproduction Link

https://stackblitz.com/edit/preact-starter-template-wkvvng?file=index.js

## Expected Results

Should wrap the element and expose it as a Preact component

## Actual Results

![image](https://user-images.githubusercontent.com/12656294/151895913-c1524853-1272-4605-9eaa-4cf658e2cabc.png)

## Browsers Affected

- [x ] Chrome
- [ x] Firefox
- [ x] Edge
- [x ] Safari 11
- [x ] Safari 10
- [ x] IE 11

**Comment by justinfagnani** [comment] 2022-02-01 00:50
Do you happen to know if Preact has a `forwardRef` equivalent, or if it's in the compat library?

**Comment by justinfagnani** [comment] 2022-03-29 22:20
Looks like we would need a way to pass in `forwardRef` from Preact: https://preactjs.com/guide/v10/switching-to-preact/#forwardref

**Comment by taylor-vann** [comment] 2022-03-30 19:06
can confirm, providing `forwardRef` from the `preact/compat` library will allow the lit-labs react wrapper to function with preact.

example:
https://stackblitz.com/edit/preact-starter-template-tihnal?file=index.js

```
/** @jsx h */
import { LitElement } from 'lit';
import { createComponent } from '@lit-labs/react';
import { h, render } from 'preact';
import * as Preact from 'preact';
import { forwardRef } from 'preact/compat';

export class SimpleGreetingElement extends LitElement {
  render() {
    return html`<p>Hello World!</p>`;
  }
}

const SimpleGreeting = createComponent(
  { ...Preact, ...{ forwardRef } },
  'simple-greeting',
  SimpleGreetingElement
);

function App() {
  return (
    <div>
      <h1>Hello</h1>
      <SimpleGreeting />
    </div>
  );
}

render(<App />, document.body);
```

**Comment by taylor-vann** [comment] 2022-04-04 17:29
@justinfagnani @alshdavid

I can confirm that including `forwardRef` from the preact `compat` library will resolve this issue.

The following is a demo of using `forwardRef` with the Lit React wrapper.
https://codesandbox.io/s/practical-christian-rstyjx?file=/src/index.js

Closing as resolved, feel free to open if issues persist <3

**Closed by taylor-vann** 2022-04-04 17:29 UTC
Labels: More Info Needed
