### ISSUE TITLE
Virtualizer.js:543 Uncaught (in promise) TypeError: Cannot destructure property 'scrollTop' of 

### ISSUE THREAD

**Issue by cintaccs** [lit/lit#4238] opened 2023-09-28 11:59 UTC
### Which package(s) are affected?

Virtualizer (@lit-labs/virtualizer)

### Description

When refreshing the parent container (pressing the refresh button at the top header) - the virtualizer should get new data content (it does) - but fails to reset/deconstruct ....

<img width="867" alt="Screenshot 2023-09-28 at 13 53 22" src="https://github.com/lit/lit/assets/4300051/34108a1c-ce5a-47fa-8453-fde9622b3586">
<img width="862" alt="Screenshot 2023-09-28 at 13 54 12" src="https://github.com/lit/lit/assets/4300051/b20c9783-017b-499a-8543-928ba68de6e1">

### Reproduction

I believe the smartest is to check whether the 'this._scrollerController' is null.

### Workaround

none

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

@lit-labs/virtualizer": "2.0.7"

### Browser/OS/Node environment

Chrome latest

**Comment by graynorton** [comment] 2023-09-28 15:10
Thanks for the report, @cintaccs. This appears to be a duplicate of #4182, a regression introduced in 2.0.5. There's a community PR to fix #4182 which I am in the process of reviewing (and trying to create a minimal repro case so we can add some tests).

I'm going to close this issue as a duplicate, but I may ping you on #4182 if I have questions.

**Closed by graynorton** 2023-09-28 15:10 UTC

**Comment by graynorton** [comment] 2023-09-29 23:02
@cintaccs I tried @-messaging you with a question in this PR:

https://github.com/lit/lit/pull/4233

...but I'm not sure whether you will have received a notification, since you weren't already participating in that discussion. When you have a chance, please take a look—thanks!

**Comment by cintaccs** [comment] 2023-10-10 09:49
> @cintaccs I tried @-messaging you with a question in this PR:
> 
> #4233
> 
> ...but I'm not sure whether you will have received a notification, since you weren't already participating in that discussion. When you have a chance, please take a look—thanks!

@lit-labs/virtualizer: 2.0.8, 

doesn't seems to solve the issue. Same error message.

**Comment by cintaccs** [comment] 2023-10-29 11:44
@graynorton FYI - 2.0.9 fixed my issue! Thanks a lot!
