### ISSUE TITLE
[labs/task] Initial pending template

### ISSUE THREAD

**Issue by a11delavar** [lit/lit#3143] opened 2022-07-18 15:15 UTC
### Which package is this a feature request for?

Task (@lit-labs/task)

### Description

I find myself not using lit's `Task` in most cases because there is no way of rendering a template **only for the initial pending state**. It would be a helpful addition to have this baked into `Task` itself, as the current implementation does not allow much tweaking.

This way you can for instance render a loading screen and then render an expensive template when the `value` is resolved, but not go back to the pending state if you were to re`run` the `Task`  for whatever reason, which leads to reconstructing the expensive template to have the pending template in between.  

### Alternatives and Workarounds

I considered deriving the `Task` class to add this option, as well as using `Task` without its `render` and handle its `value` by myself, but both won't work as the underlying `_value` also gets destroyed when `run` is called. https://github.com/lit/lit/blob/main/packages/labs/task/src/task.ts#L199-L203

**Comment by sorvell** [comment] 2022-07-19 21:37
You can do something like this by keeping a value around. Here's an example: https://lit.dev/playground/#gist=d5932cfb7a604480b9c524730391ed7c

We're considering not having task reset its value when it goes to a pending state in https://github.com/lit/lit/pull/2836

**Comment by arshia11d** [comment] 2022-07-22 09:01
> You can do something like this by keeping a value around. Here's an example: https://lit.dev/playground/#gist=d5932cfb7a604480b9c524730391ed7c

Yeah, I also did similar things, but at that point it was not ergonomic at all, and implementing it manually was in most cases more straightforward.

> We're considering not having task reset its value when it goes to a pending state in https://github.com/lit/lit/pull/2836

That is interesting, and would be helpful in some cases I suppose, however to solve the issue I'm having you need to dynamically set the `initialValue` after every fetch (?) which even possible, still isn't ergonomic at all.

**Comment by justinfagnani** [comment] 2023-07-08 02:26
I think that one way to think about Task's render() helper and this problem is that render() is there for a relatively common case where task states are mutually exclusive, but that task states aren't actually mutually exclusive to that degree and if you need finer-grained rendering that you maybe should not use render().

For example, in the PENDING status, the previous status could have been COMPLETE or ERROR and which ever it was, the `.error` or `.value` properties will retain the value from that status. Since you can access `status`, `value`, and `error`, you can write code that handles more complicated cases:

```ts
class MyElement extends LitElement {
  private task = new Task(...);
  
  render() {
    // Only render "loading" if we don't have data to show
    if (this.task.status === TaskStatus.PENDING && this.task.value === undefined) {
        return html`<p>Loading...</p>`;
    }
    if (this.task.status === TaskStatus.COMPLETE
        || this.task.status === TaskStatus.PENDING && this.task.value !== undefined) {
      return html`<p>Data: ${this.task.value}</p>`;
    }
  }
}
```

**Comment by justinfagnani** [comment] 2023-07-10 19:49
Since the task value is now preserved between runs, and there's a workaround of not using render (or accessing the task's value in render/pending). I'm going to close this as working as intended.

**Closed by justinfagnani** 2023-07-10 19:49 UTC
