### ISSUE TITLE
[labs/ssr] Access to slots during SSR

### ISSUE THREAD

**Issue by matthewp** [lit/lit#1995] opened 2021-07-06 17:02 UTC
# Description

Some components such as Shoelace's `<sl-button>` component differentiate rendering based on which slots are assigned.

When Lit renders to HTML it does not call the `slotchange`, which causes the `<sl-button>` to incorrectly render.

I think this might be a limitation of Lit's SSR implementation, which wishes to not implement a lot of DOM. Could there perhaps be an alternative API available only during SSR that a component could use to know which slots are assigned?

cc @claviska

# Steps to Reproduce

See this bug: https://github.com/shoelace-style/shoelace/issues/476

## Live Reproduction Link

The stackblitz does not do SSR.

## Expected Results

Properly render.

## Actual Results

Missing required attributes due to slotchange not firing.

## Browsers Affected

Server rendering issue only.

**Comment by claviska** [comment] 2021-07-06 17:15
The use of "slot detection" is not unique to Shoelace nor Lit components. I've seen this pattern in the wild a number of times, including in FAST components ([code example](https://github.com/microsoft/fast/blob/abe74acdb97008602fdf8193722388dbe454787f/packages/web-components/fast-components/src/button/index.ts#L40-L56)).

Using attributes such as `has-default-slot` is a stopgap, albeit a messy one. As a library author, making this "just work" is the ideal solution since it would likely work for all WCs, but I'd also be OK with opting in to some kind of Lit-provided utility if necessary.

**Comment by justinfagnani** [comment] 2021-07-08 22:13
We're discussing this. The issue is that we want to avoid requiring a slow DOM emulation and/or preventing streaming. This looks like a pretty complicated situation.

I think there are few things to consider:

* I looked at a few elements that do this and mainly they seem to set classes based on the existed (and type 😬) of slotted elements. If we look at rendering as UI = f(state), this is a gap in the declarative rendering that requires imperative code to derive state from slotted children.
* We can try to allow the existing imperative code, or build a semi-declarative API that can be implemented in SSR code as well. The declarative form would not deal in DOM events and nodes, but would probably just provide info on the directly slotted elements tag names and static attributes.
* We can test and document how to run lit-ssr with full DOM emulation like JSDOM and make a renderer that uses that to run a more complete element lifecycle. This would be much slower than the string renderer, so we'd want to be able to interleave string and DOM renderers to only run the DOM renderer for elements that need it. This would let us group elements into "fast mode" and "full DOM (slow) mode".
* I do wonder if many of the cases that set class names can be ported to work purely in CSS. Could slots and fallback content by styled so that the absence of the fallback content triggers the correct styles? Could `::slotted()` be used with positional selectors to add needed spacing to first and last elements? I think some cases would require `:has()` or a new pseudo-class for slots with slotted content, so I filed: https://github.com/WICG/webcomponents/issues/936

**Comment by matthewp** [comment] 2021-07-09 12:42
@justinfagnani Thanks! I think a CSS solution for the use-case would be best, but I don't know enough about it to say if it would be possible. 

Otherwise I think a declarative solution here would be nice and a reasonable fallback, rather than adding a separate DOM requirement just for certain elements.

**Comment by justinfagnani** [comment] 2024-10-02 01:56
It would be _extremely_ difficult for us to materialize slots during SSR, both because of the additional parsing and bookkeeping we'd have to do and because we stream out shadow root contents before the light DOM that would fill the slots.

Luckily, the `:has-slotted` pseudo-class proposal was approved and is being implemented as we speak!

Closing this issue on our end now.

**Closed by justinfagnani** 2024-10-02 01:56 UTC
Labels: Needs Discussion
