### ISSUE TITLE
Progress on Hot Module Replacement support?

### ISSUE THREAD

**Issue by Nukiloco** [lit/lit#2007] opened 2021-07-15 06:47 UTC
# Description
I know that this issue currently exists: https://github.com/lit/lit/issues/1844
Though it seems the last comment was two years ago and it doesn't seem like there has been a lot demand for Hot Module Replacement support. The code samples or temporary solutions provided didn't seem to work at all from what I been testing out so far. What is the current status on Hot Module Replacement for Lit? Also is there a temporary solution for Lit with Hot Module Replacement using Webpack? Thanks!

**Comment by Nuciloco** [comment] 2021-07-15 13:50
From one of the libraries ``custom-elements-hmr-polyfill``, I get this error ``Uncaught TypeError: Illegal constructor.`` when running ``applyPolyfill`` with any arguments.

**Comment by justinfagnani** [comment] 2021-07-15 15:41
cc @rictic

**Comment by zanettin** [comment] 2021-08-10 14:46
sorry for chiming in here as well. just faced the same issue on a nextJS app with fast refresh ` DOMException: Failed to execute 'define' on 'CustomElementRegistry` caused by the `@customElement` decorator. would a check if a name is already registered solve the issue before calling `.define()`?

**Comment by mrts** [comment] 2021-08-10 20:27
Have you tried Vite? See instructions in https://github.com/litelement-dev/lit-simple-starter-kit how to use it as recommended in #1929.

**Comment by Nuciloco** [comment] 2021-08-12 17:59
> 
> 
> Have you tried Vite? See instructions in https://github.com/litelement-dev/lit-simple-starter-kit how to use it as recommended in #1929. Here's an [overview](https://vitejs.dev/guide/why.html#slow-server-start) how Vite improves on standard hot module replacement to provide even better developer experience.

I'm not a personal fan of having to switch existing build tools (aka Webpack) for the website I'm working on. I'm not sure if this is a proper solution to Hot Module Replacement for Lit?

**Comment by thescientist13** [comment] 2021-09-02 14:25
Posted in the other issue as well, but FWIW, there is also a [community standards group for WC tracking this issue as well](https://github.com/webcomponents/community-protocols/issues/6).  

Perhaps if a "spec" can be achieved there through consensus first, it would be easier for WC libraries and tools like Lit / open-wc / etc to adopt in as close to a standards way so that all tools can achieve harmony and compatibility instead of each of them working on it independently.

----

Would it make sense to close one of these two issues in this lit repo at least?

**Comment by Nukiloco** [comment] 2021-09-25 13:53
What are the current limitations with getting hot reloading working on Lit? I know that one of them probably has to do with defining custom elements.

**Comment by kevinpschaaf** [comment] 2022-01-14 23:32
Related issue: https://github.com/lit/lit/issues/1586

**Comment by justinfagnani** [comment] 2022-09-08 18:04
Duplicate of [#1844](https://github.com/lit/lit/issues/1844)

**Closed by justinfagnani** 2022-09-08 18:04 UTC
