### ISSUE TITLE
[labs/context] Context provider controller can't be created after element is connected

### ISSUE THREAD

**Issue by nachoab** [lit/lit#3319] opened 2022-09-29 00:25 UTC
### Which package(s) are affected?

Context (@lit-labs/context)

### Description

Attaching a ContextProvider controller to an element after it has been connected is not updating consumers that have been defined earlier (using the ContextRoot)

```js
  connectedCallback() {
    super.connectedCallback();
    setTimeout(() => this.createProviderLater());
  }

  createProviderLater() {
    // this will not be listened by earlier registered consumers or mycontext
    this.provider = new ContextProvider(this, mycontext, true);
  }
```

### Reproduction

https://lit.dev/playground/#gist=7c3a835e988e8d0ee6d0d84e07adfcbc

### Workaround

I think the issue comes from the [constructor of the ContextProvider controller](https://github.com/lit/lit/blob/b225bd3ae1f03d46119650c997719b86742831fe/packages/labs/context/src/lib/controllers/context-provider.ts#L53)

Listeners should be added before the controller is added to the host:

```ts
	constructor(protected host: ReactiveElement, private context: T, initialValue?: ContextType<T>) {
		super(initialValue);
		this.attachListeners();
		this.host.addController(this);
	}
```

Otherwise hostConnected gets called which fires the 'context-provider' event. The ContextRoot instance captures it and dispatches pending context requests before listeners have been added.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

failing at 0.1.3

### Browser/OS/Node environment

Browser: Chrome 106.0.5249.61

**Comment by nachoab** [comment] 2022-09-29 01:00
I think there might be another problem with the context-root [here](https://github.com/lit/lit/blob/b225bd3ae1f03d46119650c997719b86742831fe/packages/labs/context/src/lib/context-root.ts#L85) related with this issue

Shouldn't ```composedPath()[0] ``` be stored instead of ```target``` here?
Otherwise, we'll not be dispatching the event from the same target again in some cases

```js
    const request: PendingContextRequest = {
      element: ev.target as HTMLElement,
      callback: ev.callback,
    };
```

**Comment by justinfagnani** [comment] 2022-10-27 21:58
Duplicate of https://github.com/lit/lit/issues/3251

**Closed by justinfagnani** 2022-10-27 21:58 UTC
