### ISSUE TITLE
[ssr] Lit SSR breaks Sass with polyfill

### ISSUE THREAD

**Issue by FredKSchott** [lit/lit#2393] opened 2022-01-07 23:50 UTC
# Description

The required Lit SSR global window polyfill breaks Sass, and potentially other tools. cc @jaydanurwin who ran into this issue while trying to record a video on using Lit + Sass in Astro.

# Steps to Reproduce

1. Write this code in Node.js

```
await import('@lit-labs/ssr/lib/install-global-dom-shim.js');
// then, Sass fails to load
await import('sass');
```

2. See error: `"Cannot assign to read only property 'fs' of object '#<Object>'`

Relevant: https://github.com/mbullington/node_preamble.dart/issues/26

**Comment by jaydanurwin** [comment] 2022-01-08 00:05
Thanks for filing this @FredKSchott. It's not a complete project breaker but it would be nice to use Sass in Astro alongside Lit SSR components.

**Comment by jonathantneal** [comment] 2022-01-08 00:39
Noting the bug is probably with Sass. https://github.com/mbullington/node_preamble.dart/issues/26

**Comment by aomarks** [comment] 2022-01-08 16:58
https://github.com/lit/lit/issues/2391 is a similar issue where the presence of the window polyfill breaks the behavior of another library.

Maybe we could swap in and out the window polyfill only when are rendering (using AsyncLocalStorage?) as a general fix for this class of issue.

**Comment by justinfagnani** [comment] 2022-01-19 06:31
This shouldn't be an issue if we load all the code into a fresh VM context, like we do with the JS module loader. Since we want a version that can work without the `--experimental-vm-modules` flag, maybe there's a way to use plain dynamic `import()` in a classic script vm context so that we get a fresh global, just without the module loading hooks.

**Comment by aomarks** [comment] 2022-01-20 21:51
> This shouldn't be an issue if we load all the code into a fresh VM context, like we do with the JS module loader. Since we want a version that can work without the `--experimental-vm-modules` flag, maybe there's a way to use plain dynamic `import()` in a classic script vm context so that we get a fresh global, just without the module loading hooks.

Unfortunately this is not possible because dynamic `import()` in any isolated vm context always requires the `--experimental-vm-modules` flag. From the [docs](https://nodejs.org/api/vm.html#class-vmscript):

```
importModuleDynamically <Function> Called during evaluation of this module when import()
is called. If this option is not specified, calls to import() will reject with
`ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING`. This option is part of the experimental modules API.
We do not recommend using it in a production environment.
```

@FredKSchott Speaking of that, have you looked into using the isolated vm context approach for Lit SSR in Astro? It does require the `--experimental-vm-modules` flag, and I suppose you could potentially include it in your `astro` binary heading (e.g. `#!/usr/bin/env node --experimental-vm-modules`) so that users don't actually need to know about it. This approach should provide full isolation from any interactions with other libraries.

If that's not an option though, we're also going to start looking into using Node worker threads to provide isolation, which doesn't require any experimental flags. (@thescientist13 I noticed you are looking into that too! Curious if you have any findings so far.).

Another reason that Astro and other tools may want an isolated rendering approach is for watch modes, which often work with a loop all within the same process. There is no way to bust the ESM cache in Node, so updating a component definition won't have any effect in that case until the process is restarted. @FredKSchott have you run into this problem with watch mode using the global style Lit SSR technique yet?

**Comment by thescientist13** [comment] 2022-01-21 14:50
Hey @aomarks 

I may have circumvented this issue myself without the use of VM context unintentionally using Workers because as you point out here
> There is no way to bust the ESM cache in Node, so updating a component definition won't have any effect in that case until the process is restarted.

I got my solution from [this NodeJS thread](https://github.com/nodejs/modules/issues/307#issuecomment-858729422) though I had never used them before, but they seem to work quite well and also seem to provide isolation for this and future SSR libs since I'm sure they'll all have to do some sort of polyfilling in the shared NodeJS runtime so seemed like I was able to get two wins out of this solution. (I'm also hoping to collaborate with the team on one for native `HTMLElement` soon too if anyone is up for it - #2092 🤞 )  

----

Also, this is a pretty cool tip! 
> (e.g. `#!/usr/bin/env node --experimental-vm-modules`) 

I had wanted to explore VM Modules as well but wasn't sure how to integrate into a CLI, so this is a super useful!  Thanks!  🙏

**Comment by justinfagnani** [comment] 2022-01-21 16:42
I'm hopeful that Workers... work. It'd be nice to have an isolation and module cache-busting solution that work without flags.

**Comment by aomarks** [comment] 2022-01-24 19:17
> What I've done in other projects and would recommend for Lit is to not depend on browser globals in your core modules but instead use some pattern like this:

Hmm, interesting. I'm not sure that removing _all_ global object augmentation is where we want go from a DX perspective, because it means that very common and core patterns for writing components will break in SSR. The most obvious example of that is `customElements.define`, which every component uses (technically ones that use the Lit decorator could work, because we could update the decorator to check in an alternative spot for that API -- but I think we should consider the vanilla JS use case as core).

However, it may be feasible to simply stop assigning `global.window`. `window` is the property that libraries like SASS are looking at to determine whether they are in browser vs node. We could continue to assign all of the web APIs that components need directly to `global`, but just not assign `window`.

That way, code that assumes an API is defined can just write e.g. `customElement.define` instead of `window.customElement.define` (which is mostly what's done anyway). And code that needs to check for a possibly `undefined` property (like a few spots in Lit where we probe for browser features) can be updated to check `globalThis.<property>` instead.

> If you were to import a module in both contexts they would be separate instances and have separate state. This leads to hard to track down bugs.

Could you elaborate a little more on what kind of state you're thinking of here, maybe an example? (Not doubting at all, just trying to understand more deeply).

**Comment by matthewp** [comment] 2022-01-24 19:31
That sounds like a good compromise @aomarks.

> Could you elaborate a little more on what kind of state you're thinking of here, maybe an example? (Not doubting at all, just trying to understand more deeply).

Yep, sure, here's an example:

__counter.js__
```js
export let count = 0;

export const increment = () => count++;
```

__render-template.js__
```js
import {render} from '@lit-labs/ssr/lib/render-lit-html.js';
import {html} from 'lit';
import {count} from './counter.js';
export const renderTemplate = () => {
  return render(html`<span>Count: ${count}</span>`);
};
```

__main.js__
```js
import {renderModule} from '@lit-labs/ssr/lib/render-module.js';
import {increment} from './counter.js';

increment();

const ssrResult = await (renderModule(
  './render-template.js',
  import.meta.url, 
  'renderTemplate',
));
```

This will produce `<span>Count: 0</span>` when it is expected to produce `<span>Count: 1</span>`. This is because there are 2 instances of `counter.js`.

**Comment by justinfagnani** [comment] 2022-01-24 21:38
We can't control what globals 3rd party code might access, so I don't think we can say yet exactly what globals, including `window` we can avoid defining.

I don't see why Sass and components need to run in the same context ever. Seems like a much better solution to isolate component code with it's own globals that don't interfere with anyone else.

**Comment by matthewp** [comment] 2022-01-25 12:41
It's not that Sass needs to run in the same context, it's that a user's application, including all of their dependencies, need to run in the same context, because global state is very common and having multiple contexts means difficult to track down bugs.

It's one thing for a user to set up a separate context themselves, knowingly, but it's another for a library to do it for them via an abstraction so that the code looks like, to them, as though it were running in the same context.

**Comment by augustjk** [comment] 2022-02-05 00:24
Here are a few things we found after digging around.

Part of the problem is how the `sass` npm package, which is compiled to js from dart, tries to figure out its running environment. As mentioned in the issue linked by jonathantneal mentioned above, https://github.com/mbullington/node_preamble.dart/blob/master/lib/preamble.js#L41-L53 checks for `window` to see if it's running in Node to do its own polyfilling. The more problematic portion is that the compilation from dart to js also adds this check for the presence of `document` in global https://github.com/dart-lang/sdk/blob/main/pkg/compiler/lib/src/js_emitter/main_call_stub_generator.dart#L70-L73 which breaks sass when run after the DOM polyfill.

Another issue seems to be arising due to this line https://github.com/withastro/astro/blob/main/packages/renderers/renderer-lit/server-shim.js#L4. I'm not sure on what the purpose of this is is but along with this Window proxy https://github.com/lit/lit/blob/main/packages/labs/ssr/src/lib/dom-shim.ts#L190-L201 it makes it so that `global` isn't exactly the full node `global` down the line. I think we can investigate looking into removing the Window proxy from our dom shim but perhaps the line from astro lit renderer's server-shim could also be removed.

A couple potential solutions:

Firstly, loading the sass module before any of the DOM shimming by adding `import 'sass';` to the top of the `@astrojs/renderer-lit/server-shim.js` completely solves this issue. I don’t know if it would be possible for Astro to let Vite handle the styling preprocessors do their thing first before loading up the shims and doing the rendering, but that should allow sass to not break.

Otherwise, we'd need the dart2js compiler to do something besides just checking for absence `document` in global (perhaps check for the presence of `process`?) to tell how the script should be executed, along with fixing the Window proxy/global issue above. Not polyfilling `window` alone will not fix this since `document` will still be on there.

**Comment by justinfagnani** [comment] 2022-02-05 01:27
Thanks for the details @augustjk!

**Comment by matthewp** [comment] 2022-02-07 18:43
Thanks for doing this research @augustjk. Just going to comment on a couple of your observations:

>  I think we can investigate looking into removing the Window proxy from our dom shim but perhaps the line from astro lit renderer's server-shim could also be removed.

Quite possibly. I don't remember the details for why that line was added but happy to try and remove it and see if that helps.

> Firstly, loading the sass module before any of the DOM shimming by adding import 'sass'; to the top of the @astrojs/renderer-lit/server-shim.js completely solves this issue. 

We can't/shouldn't do that because sass is not a dependency of that package, it's a dependency that a user might load.

>  I don’t know if it would be possible for Astro to let Vite handle the styling preprocessors do their thing first before loading up the shims and doing the rendering, but that should allow sass to not break.

Unfortunately not. The renderer needs to be loaded to do SSR. Sass might not be loaded until lazily so because an HTTP request needs it (which would be after rendering).

**Comment by augustjk** [comment] 2022-02-07 23:55
Even simpler, adding
```js
document.currentScript = null;
```
as suggested [here](https://github.com/dart-lang/sdk/issues/48336#issuecomment-1032054223) makes the sass script run.

**Comment by aomarks** [comment] 2023-01-09 21:53
`@lit-labs/ssr` v3.0.0 was just published, which has the following changes that should resolve this issue:

- The global DOM shim no longer sets `window`.
- The global DOM shim is no longer required at all! Lit will now automatically import and use shims for the APIs it needs when running in Node.

So, if you're using `import {render} from '@lit-labs/ssr/lib/render-with-global-dom-shim.js'`, you should now instead use `import {render} from '@lit-labs/ssr/lib/render-lit-html.js'` -- and you can remove any imports for `@lit-labs/ssr/dom-shim.js` and `@lit-labs/ssr/install-global-dom-shim.js`

**Closed by aomarks** 2023-01-09 21:53 UTC
