### ISSUE TITLE
Render issue with selected option in firefox

### ISSUE THREAD

**Issue by benoit-romito** [lit/lit#3343] opened 2022-10-11 08:24 UTC
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

**Summary:**
When changing the currently selected  `<option>`  of a  `<select> ` tag in Firefox, using the `render()` function. An unexpected behavior happens. See the full reproduction case in copy. The problem does not occur on Chrome browser.

**Details:**
I have a `<select>` tag containing the 12 monthes of the year and two buttons `prev` and `next`. When a button is pressed, the current date is modified and a render is triggered. In the render the month of the current date is selected using the `selected` attribute of the corresponding `<option>`. Il you press the `prev` button 13 times, the `<select>` elements gets stucked at `Janvier`. 

If you look at the dom elements while doing the previous action, the selected attributes are correctly set on the right elements.
 

### Reproduction

```
import "./styles.css";
import { html, LitElement } from "lit";
import { keyed } from "lit/directives/keyed.js";

class MyElement extends LitElement {
  static get properties() {
    return {
      mood: { type: String }
    };
  }

  constructor() {
    super();
    this.mood = "happy";
    this.currentDate = new Date();
  }

  getMonthList(locales = null, format = "long") {
    const year = new Date().getFullYear();
    const monthList = [...Array(12).keys()]; // [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    const formatter = new Intl.DateTimeFormat(locales, {
      month: format
    });

    const getMonthName = (monthIndex) =>
      formatter.format(new Date(year, monthIndex));

    return monthList.map(getMonthName);
  }

  capitalizeFirst(str) {
    if (str != null && str.length > 0) {
      return str[0].toUpperCase() + str.substring(1);
    }
    return str;
  }

  render() {
    const monthList = this.getMonthList("fr-FR", "long").map((month) =>
      this.capitalizeFirst(month)
    );
    const monthOptions = monthList.map(
      (month, index) =>
        html`${keyed(
          index,
          html`
            <option
              value="${index}"
              ?selected=${this.currentDate.getMonth() === index}
              >${month}</option
            >
          `
        )}`
    );
    return html` <button @click=${this.onprev}>prev</button>
      <select class="str-datepicker-select">
        ${monthOptions}
      </select>
      <button @click=${this.onnext}>next</button>`;
  }

  onprev(evt) {
    this.currentDate.setMonth(this.currentDate.getMonth() - 1);
    this.requestUpdate();
  }
  onnext(evt) {
    this.currentDate.setMonth(this.currentDate.getMonth() + 1);
    this.requestUpdate();
  }
}

customElements.define("test-element", MyElement);
```

### Workaround

I have not found any workarount.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

tested with 2.2.2, 2.4.0

### Browser/OS/Node environment

Browser: Firefox 105.0.3 (64 bits) Windows

**Comment by augustjk** [comment] 2022-10-11 22:33
Repro in playground: https://lit.dev/playground/#gist=888beb24734a3bf46a470e4c5b6811c1

This is an interesting finding. I can confirm I see the same thing when trying this in Firefox. The select seems to get stuck on "Janvier" even though the `.selectedDate` prop on `<test-element>` is different, as well as the selected attribute on the corresponding `<option>` element. In Safari, it gets stuck on the first selected option.

I don't know why this behavior is different in the browsers. Per MDN, the selected attribute really is only for specifying the initial selection. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option#attr-selected

The fix for it is to actually bind the `value` property on the `<select>` element to the current date. Like so:
https://lit.dev/playground/#gist=264afd68934dae28d7015f8bd85837e4

This works for Chrome, Firefox, and Safari.

You should also consider adding a change event handler for the select element that updates `this.currentDate` for when the user actually uses the select dropdown rather than the prev and next buttons.

**Comment by sorvell** [comment] 2022-10-12 01:47
Just a quick add to @augustjk 's answer which is definitely the best approach. It's also possible to bind the `selected` property instead of the attribute to avoid the core issue: https://lit.dev/playground/#gist=6795e869d3bfbbda311ad394e3d65b82

**Comment by benoit-romito** [comment] 2022-10-12 08:32
Hi, thank you @augustjk and @sorvell for your detailed answers. Using `.value=` on the `<select>` tag works great for the month example.

While implementing this solution in another use case, I encountered a similar issue : 
```
// import "./styles.css";
import { html, LitElement } from "lit";
import { keyed } from "lit/directives/keyed.js";

class MyElement extends LitElement {
  static get properties() {
    return {
      mood: { type: String }
    };
  }

  constructor() {
    super();
    this.mood = "happy";
    this.currentDate = new Date();
  }

  render() {
    const yearOptions = [];
    for (let i = -1; i <= 1; i++) {
      const year = this.currentDate.getFullYear() + i;
      yearOptions.push(html`${keyed(year, html`
        <option value=${year} ?selected=${i == 0}>${year}</option>
      `)}`);
    }
    
    return html`<select @change=${this.yearChange} .value=${this.currentDate.getFullYear()}>
        ${yearOptions}
      </select>`;
  }
  
  yearChange(evt) {
    console.log(evt.target.value);
    this.currentDate.setFullYear(evt.target.value);
    this.requestUpdate();
  }
}

customElements.define("test-element", MyElement);
```

In this example the `<select>` elements has a sliding window of the previous year, the current year and the next year, regarding the current date. 

In Firefox, when I click the 2023 option, the new `<option>` tags are well rendered by lit, but it does not take the value property because it stays in 2022.

In Chrome, no problem.

_I found a "workaround" by using a `queryselector` and setting the value of the `select` in javascript in the updated method, but I is not really clean in my opinion.

Thank you

**Comment by augustjk** [comment] 2022-10-12 20:57
I think that problem is again due to the unreliable behavior when the children `<option>` elements get modified during update without its parent `<select>` element.

One way to ensure that they all update together is to use the `keyed()` directive around the entire template containing `<select>` so that `<select>` and children `<options>` are updated together.

https://lit.dev/playground/#gist=49a6650800e50f9bee893b360105be25

**Comment by benoit-romito** [comment] 2022-10-13 07:22
hi @augustjk, clever workaround. It works well, a bit hacky but it works thanks for you answers :) !

**Comment by augustjk** [comment] 2022-10-13 23:41
Closing this as solved. Please feel free to re-open or start a [discussion](https://github.com/lit/lit/discussions) if you encounter additional problems!

**Closed by augustjk** 2022-10-13 23:41 UTC
