### ISSUE TITLE
[labs/ssr] Support rendering in Cloudflare workers

### ISSUE THREAD

**Issue by theneverstill** [lit/lit#3908] opened 2023-05-18 14:24 UTC
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

SSR (@lit-labs/ssr)

### Description

It would be greatly appreciated if SSR worked in Cloudflare workers (NOT talking about "service workers"). With the right polyfills Cloudflare workers are very similar to Node.

It would appear like almost everything works as expected, but when I try to deploy the worker to Cloudflare (which is a build/bundle step) I get an error: `Uncaught ReferenceError: window is not defined`

I believe this is because the code is building/importing/running thinking the environment is the browser (rather than node).

Vite plugin SSR had a similar issue and hopefully similar fix: https://github.com/brillout/vite-plugin-ssr/issues/130

Thanks!!

### Alternatives and Workarounds

Don't use Cloudflare workers for SSR.

**Comment by augustjk** [comment] 2023-05-19 21:44
Duplicate of #3907

**Closed by augustjk** 2023-05-19 21:44 UTC
