### ISSUE TITLE
Does the module system have to be that complicated?

### ISSUE THREAD

**Issue by jrtp** [lit/lit#2408] opened 2022-01-15 13:48 UTC
Description
Getting started with lit is very annoying due to the module system and common circumstances that make it even harder to get started.

npm i lit works but for some reason all import statements are without correct relative paths.
Imports pointing to just the folder are als prone to errors since its quite some work to setup servers to make that work out of the box
Its just a bad experience for an otherwise great product.

How about the option on lit.dev to create a good old fashioned minifed version including everything needed (maybe configurable) that can be simply included as normal js and thats it on top of utilizing the hell out of the cumbersome module system?

**Comment by jrtp** [comment] 2022-01-15 14:10
I just found out that with 2.0 it also works nicely with unpkg - something that is not written on https://lit.dev/docs/getting-started/ for 2.0, only for 1.0. With that starting is quite easy, maybe that could be included again at least. As written above setting it up from scratch is not straight forward due to many reasons.

**Comment by thescientist13** [comment] 2022-01-17 15:31
> but for some reason all import statements are without correct relative paths.

Yes, Lit uses bare ESM import specifiers which does indeed require some sort of processing / development help.  I think the assumption is that if you're pulling from npm, you're already using some sort of build tooling already, though I could see how making that a bit more explicit up front in the [getting started docs](https://lit.dev/docs/getting-started/) would be useful under the npm section at least, maybe by linking to the [_Development_ page](https://lit.dev/docs/tools/development/) of the docs?  I think it's pretty common for beginners at least to struggle a bit understanding how Node fits into a browser based workflow and the bit of "glue" needed there.

Though the docs provide links to starter kits, a good option for hand-rolling could be to use an up and coming standard call [import maps](https://github.com/WICG/import-maps), using the [**es-module-shims**](https://github.com/guybedford/es-module-shims).  (my preference)

**Comment by kevinpschaaf** [comment] 2022-02-10 20:30
Closing as dupe of #2272. The work of creating a minified bundle on each release available on a CDN or for download is done, and will roll out from our next release.

**Closed by kevinpschaaf** 2022-02-10 20:30 UTC
