### ISSUE TITLE
Legacy browser version compatibility of 'flat' API

### ISSUE THREAD

**Issue by Josp3r** [lit/lit#4695] opened 2024-07-08 06:55 UTC
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

![image](https://github.com/lit/lit/assets/100178848/0fe4b830-659e-42c7-9d5f-94fcc569abbf)

I wanna use lit for those legacy browser versions like chrome 65. core-js polyfill is not work on this scene cause those browser API is existed but has bugs.
so why not use other API to avoid these issues.

[@lit/reactive-element/development/reactive-element.js]

<img width="677" alt="image" src="https://github.com/lit/lit/assets/100178848/8d821ae2-0a01-41ae-80ba-d93942daf8b1">

Please review it, thx.

### Alternatives and Workarounds

Use other array API or use lodash.flatten

**Comment by Josp3r** [comment] 2024-07-08 15:12
> The posted screenshot is confusing as it appears that `Array.flat` currently has > [96%](https://caniuse.com/?search=Array.flat) support.
> 
> In general, Lit uses the modern web platform as much as is practically possible. While changing this one thing is possible, it would add to support burden and likely reveal additional issues. Chrome 65 is > 6 years old and it's just impractical directly to support really old browsers.
> 
> I would suggest pushing more on using polyfills here and addressing their limitations directly.

Alright, because this scenario requires lit to cover as many old browsers as possible, when I looked up the compatibility of web components and found it to be Chrome 54^, I personally believe that lit core should be able to achieve this compatibility by only using the web component polyfill. However, if it includes some other polyfills, this will shrink the platform compatibility range of lit-driven web components, which is not an intuitive thing. Of course, if lit is certain that it will not maintain consistency for these platforms higher than the minimum web component compatibility, then I will have to polyfill them myself. If it is confirmed that these issues will not be supported, please let me know. Thank you.

**Comment by sorvell** [comment] 2024-07-09 22:47
Lit's support for legacy browsers is [documented here](https://lit.dev/docs/v2/tools/requirements/#building-for-legacy-browsers).

**Comment by justinfagnani** [comment] 2024-10-02 01:39
It's import to us to be able to use widely-supported, but modern APIs, in order to reduce our code size and take advantage of native perf. It's possible to install a polyfill for Array.flat, and that's fits with our browser support policy.

Thanks for the report, but closing this as working as intended.

**Closed by justinfagnani** 2024-10-02 01:39 UTC
