### ISSUE TITLE
render() seems to omit updating nested <template> elements

### ISSUE THREAD

**Issue by madfriend** [lit/lit#2003] opened 2021-07-14 14:57 UTC
# Description

I am trying to render a TemplateInstance with `<template>` element inside containing dynamic value: 

https://lit.dev/playground/#project=W3sibmFtZSI6InNjcmlwdC50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIHJlbmRlcn0gZnJvbSAnbGl0JztcblxuY29uc3QgdmFyaWFibGUgPSBcIldvcmxkIVwiO1xuY29uc3QgY29udGFpbmVyID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoXCJjb250YWluZXJcIik7XG5jb25zdCBkZWJ1ZyA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKFwiZGVidWdcIik7XG5cbmNvbnN0IHRlbXBsYXRlID0gaHRtbGBIZWxsbywgPHRlbXBsYXRlPiR7dmFyaWFibGV9PC90ZW1wbGF0ZT5gO1xucmVuZGVyKHRlbXBsYXRlLCBjb250YWluZXIpO1xuY29uc3QgcmF3VGV4dCA9IGNvbnRhaW5lci5pbm5lckhUTUw7XG5cbnJlbmRlcihyYXdUZXh0LCBkZWJ1Zyk7XG4ifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPGhlYWQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vc2NyaXB0LmpzXCI-PC9zY3JpcHQ-XG48L2hlYWQ-XG48Ym9keT5cbiAgPGgxPlJlbmRlcmVkPC9oMT5cbiAgPGRpdiBpZD1cImNvbnRhaW5lclwiPjwvZGl2PlxuICA8aDI-aW5uZXJIVE1MPC9oMj5cbiAgPGRpdiBpZD1cImRlYnVnXCI-PC9kaXY-XG48L2JvZHk-XG4ifV0

Seems that `render()` never substitutes the dynamic part with actual value if dynamic part is inside `<template>` (see demo). I've found that the tree walker does not iterate inside the `<template>` elements (since they have no children: https://jsfiddle.net/gs3myrL2/). Could there be any workaround?

## Expected Results

I expected the dynamic value to be in place. Oddly enough, this [worked with lit-html@1.2.1](https://stackblitz.com/edit/lit-html-nxkdc4?devtoolsheight=33&file=src/index.js)

## Actual Results

A stub comment (`<!--?lit$953312196$-->`) in stead of value.

## Browsers Affected

- [x] Chrome (only checked in Chrome)
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by justinfagnani** [comment] 2021-07-14 16:10
Duplicate of #1737

**Closed by justinfagnani** 2021-07-14 16:10 UTC
